/*****************************************************************************/
/********** !!! WARNING: CODE GENERATED BY TAPROOT. DO NOT EDIT !!! **********/
/*****************************************************************************/

/*
 * Copyright (c) 2024 Advanced Robotics at the University of Washington <robomstr@uw.edu>
 *
 * This file is part of Taproot.
 *
 * Taproot is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Taproot is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Taproot.  If not, see <https://www.gnu.org/licenses/>.
 */

#ifndef TAPROOT_ALIGNING_ENCODER_HPP_
#define TAPROOT_ALIGNING_ENCODER_HPP_

#include "multi_encoder.hpp"

namespace tap::encoder
{
/**
 * Takes in COUNT encoders and chooses one to align the rest of the encoders to
 */
template <uint32_t COUNT>
class AligningEncoder : public MultiEncoder<COUNT>
{
public:
    AligningEncoder(std::array<EncoderInterface*, COUNT> encoders, uint32_t index)
        : MultiEncoder<COUNT>(encoders),
          index(index)
    {
        this->seenEncoders |= 1 << index;  // aligning encoder defaults as "seen" because it doesn't
                                           // make sense to align to an invalid encoder
    }

    tap::algorithms::WrappedFloat getPosition() const override
    {
        syncEncoders();
        int onlineEncoders = 0;
        float position = 0;

        for (uint32_t i = 0; i < COUNT; i++)
        {
            if (this->validEncoder(i))
            {
                position += this->encoders[i]->getPosition().getUnwrappedValue();
                onlineEncoders += 1;
            }
        }
        return tap::algorithms::WrappedFloat(
            onlineEncoders == 0 ? 0 : position / onlineEncoders,
            0,
            static_cast<float>(M_TWOPI));
    }

    float getVelocity() const override
    {
        syncEncoders();
        int onlineEncoders = 0;
        float velocity = 0;

        for (uint32_t i = 0; i < COUNT; i++)
        {
            if (this->validEncoder(i))
            {
                velocity += this->encoders[i]->getVelocity();
                onlineEncoders += 1;
            }
        }
        return onlineEncoders == 0 ? 0 : velocity / onlineEncoders;
    }

    void syncEncoders() const override
    {
        if (this->validEncoder(index))
        {
            for (uint32_t i = 0; i < COUNT; i++)
            {
                if (i != index)
                {
                    bool online = this->encoders[i] != nullptr && this->encoders[i]->isOnline();
                    if (online && !this->seenEncoder(i))
                    {
                        this->seenEncoders |= 1 << i;
                        this->encoders[i]->alignWith(this->encoders[index]);
                    }
                    else if (!online)
                    {
                        this->seenEncoders &= ~(1 << i);
                    }
                }
            }
        }
    }

private:
    uint32_t index;
};
}  // namespace tap::encoder

#endif