#ifndef __ROBOT_TYPE_HPP__
#define __ROBOT_TYPE_HPP__
// #define TARGET_STANDARD_BLASTOISE
// #define TARGET_STANDARD_WARTORTLE
#define TARGET_STANDARD_SQUIRTLE
// #define TARGET_STANDARD_2023
// #define TARGET_HERO
// #define TARGET_AERIAL
// #define TARGET_SENTRY
// #define TARGET_ENGINEER
// #define TARGET_SWERVE_ENGINEER
// #define TARGET_CVTESTBENCH
// #define TARGET_TURRET

#endif