#ifndef __ROBOT_TYPE_HPP__
#define __ROBOT_TYPE_HPP__
#define TARGET_STANDARD
// #define TARGET_HERO
// #define TARGET_ENGINEER
// #define TARGET_AERIAL
// #define TARGET_SENTRY
// #define TARGET_SWERVE_STANDARD
// #define TARGET_SWERVE_ENGINEER
#define TOKYO_COMPATIBLE
#endif