#ifndef __ROBOT_TYPE_HPP__
#define __ROBOT_TYPE_HPP__
#define TARGET_STANDARD_JERRY
// #define TARGET_STANDARD_BALTHAZAR
// #define TARGET_HERO
// #define TARGET_AERIAL
// #define TARGET_SENTRY
// #define TARGET_ENGINEER
// #define TARGET_CVTESTBENCH
// #define TARGET_TURRET

#endif