/*****************************************************************************/
/********** !!! WARNING: CODE GENERATED BY TAPROOT. DO NOT EDIT !!! **********/
/*****************************************************************************/

/*
 * Copyright (c) 2020-2021 Advanced Robotics at the University of Washington <robomstr@uw.edu>
 *
 * This file is part of Taproot.
 *
 * Taproot is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Taproot is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Taproot.  If not, see <https://www.gnu.org/licenses/>.
 */

#ifndef TAPROOT_COMMAND_MAPPER_HPP_
#define TAPROOT_COMMAND_MAPPER_HPP_

#include <memory>
#include <vector>

#include "tap/communication/serial/remote.hpp"
#include "tap/control/command_mapping.hpp"
#include "tap/util_macros.hpp"

namespace tap
{
namespace control
{
class TriggerBinding;

/**
 * Class that controls mapping triggers or remote state to actions. Currently supports
 * both triggers and command mappings, but will eventually fully migrate to using triggers,
 * which, unlike command mappings, do not require remote state tracking and do not run into
 * state transition restrictions.
 *
 * Triggers are automatically registered with the CommandScheduler via TriggerBindings
 * that are created when a condition (whileTrue, onTrue, etc.) is bound to the Trigger.
 *
 * For example, the command `coolCommand` will be called while the left switch is in the
 * up position by calling whileTrue on a trigger. This can be done inline because whileTrue
 * and the other trigger bindings return Triggers themselves.
 * ```
 * Trigger leftSwitchUp(
 *      drivers(),
 *      TriggerHelpers::checkSwitchState(drivers(), Remote::Switch::LEFT_SWITCH,
 * Remote::SwitchState::UP)).whileTrue(&coolCommand);
 * ```
 *
 * All the remote mappings will be handled here. One passes a RemoteMapState and a set
 * of `Command`s for which the RemoteMapState is mapped to a `CommandMapping`
 * sub-object. Once a command mapping is created, pass this command mapping to
 * the `CommandMapper`'s `addMap` function. This will register the mapping such
 * that the `CommandMapping`'s `executeCommandMapping` function will be called
 * each time new remote information is received.
 *
 * For example, given the command `coolCommand`, to map a hold mapping
 * to the left switch in the up position, we define a `HoldCommandMapping`
 * and then add it to the `CommandMapper` as follows (where `drivers` is assumed
 * to be a global drivers object that has a `CommandMapper` object):
 *
 * ```
 * HoldCommandMapping leftSwitchUp(
 *      drivers(),
 *      {&coolCommand},
 *      RemoteMapState(Remote::Switch::LEFT_SWITCH, Remote::SwitchState::UP));
 *
 * drivers->commandMapper.addMap(&leftSwitchUp);
 * ```
 *
 * @note Only unique RemoteMapStates can be added to the CommandMapper. This ensures
 *      a user will not accidently map two `Command`s to the same RemoteMapState without
 *      knowing they did so. Instead, the user must explicitly add `Command`s to a common
 *      vector that maps to a single RemoteMapState.
 */
class CommandMapper
{
public:
    DISALLOW_COPY_AND_ASSIGN(CommandMapper)
    mockable ~CommandMapper();
    explicit CommandMapper(Drivers *);

    /**
     * Execute all trigger bindings added to `triggerBindings`
     */
    mockable void pollTriggerBindings();

    /**
     * Adds the TriggerBinding to `triggerBindings`.
     *
     * @param[in] binding A pointer to the TriggerBinding to be added.
     */
    mockable void addTriggerBinding(std::unique_ptr<TriggerBinding> binding);

    /**
     * @return the number of trigger bindings in the mapper.
     */
    mockable std::size_t getBindingSize() const { return triggerBindings.size(); }

    /**
     * @return The TriggerBinding located at the specificed index, or
     *      `nullptr` of the index is out of bounds.
     */
    mockable const TriggerBinding *getBindingAtIndex(std::size_t index) const;

    /**
     * Iterates through all the current mappings to see which buttons are pressed
     * in order to determine which commands should be added to or removed from the scheduler.
     * Call when new remote information has been received.
     */
    mockable void handleKeyStateChange(tap::control::GenericRemoteMapState &mapState);

    /**
     * Verifies the mapping passed in can be added to `commandsToRun`
     * and if possible adds the mapping.
     *
     * @param[in] mapping A pointer to the CommandMapping to be added. The
     *      command mapper is not responsible for memory deallocation of this
     *      command mapping.
     */
    mockable void addMap(std::unique_ptr<CommandMapping> mapping);

    /**
     * @return the number of command mappings in the mapper.
     */
    mockable std::size_t getCommandMappingSize() const { return commandsToRun.size(); }

    /**
     * @return The CommandMapping located at the specificed index, or
     *      `nullptr` of the index is out of bounds.
     */
    mockable const CommandMapping *getCommandMappingAtIndex(std::size_t index) const;

private:
    std::vector<std::unique_ptr<TriggerBinding>> triggerBindings;
    std::vector<std::unique_ptr<CommandMapping>> commandsToRun;
};  // class CommandMapper

}  // namespace control
}  // namespace tap

#endif  // TAPROOT_COMMAND_MAPPER_HPP_
