/*****************************************************************************/
/********** !!! WARNING: CODE GENERATED BY TAPROOT. DO NOT EDIT !!! **********/
/*****************************************************************************/

/*
 * Copyright (c) 2020-2021 Advanced Robotics at the University of Washington <robomstr@uw.edu>
 *
 * This file is part of Taproot.
 *
 * Taproot is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Taproot is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Taproot.  If not, see <https://www.gnu.org/licenses/>.
 */

#ifndef TAPROOT_INSTANT_COMMAND_HPP_
#define TAPROOT_INSTANT_COMMAND_HPP_

#include <array>
#include <cstring>
#include <functional>
#include <unordered_set>
#include <vector>

#include "tap/drivers.hpp"

#include "command.hpp"
#include "command_scheduler.hpp"
#include "repeat_command.hpp"
#include "subsystem.hpp"

namespace tap
{
namespace control
{
template <size_t SUBSYSTEMS>
/**
 * A class for a command that runs once and then finishes. Deschedules any commands with conflicting
 * subsystems before it executes, then reschedules those descheduled commands.
 */
class InstantCommand : public Command
{
public:
    InstantCommand(
        std::function<void()> actionToRun,
        std::array<Subsystem *, SUBSYSTEMS> dependencies)
        : Command(),
          actionToRun(actionToRun)
    {
        for (Subsystem *dep : dependencies) addSubsystemRequirement(dep);
    }

    bool isReady() override { return true; }

    void initialize() override { actionToRun(); }

    void execute() override {}

    void end(bool) override {}

    bool isFinished() const override { return true; }

    const char *getName() const override { return "instant command"; }

private:
    std::function<void()> actionToRun;
};
}  // namespace control
}  // namespace tap

#endif