var annotated_dup =
[
    [ "modm", null, [
      [ "atomic", null, [
        [ "Container", "classmodm_1_1atomic_1_1_container.html", "classmodm_1_1atomic_1_1_container" ],
        [ "Flag", "classmodm_1_1atomic_1_1_flag.html", "classmodm_1_1atomic_1_1_flag" ],
        [ "Queue", "classmodm_1_1atomic_1_1_queue.html", "classmodm_1_1atomic_1_1_queue" ]
      ] ],
      [ "accessor", null, [
        [ "Flash", "classmodm_1_1accessor_1_1_flash.html", null ],
        [ "Ram", "classmodm_1_1accessor_1_1_ram.html", null ]
      ] ],
      [ "can", null, [
        [ "StandardIdentifier", "structmodm_1_1can_1_1_standard_identifier.html", null ],
        [ "StandardMask", "structmodm_1_1can_1_1_standard_mask.html", null ],
        [ "ExtendedIdentifier", "structmodm_1_1can_1_1_extended_identifier.html", null ],
        [ "ExtendedMask", "structmodm_1_1can_1_1_extended_mask.html", null ],
        [ "Message", "structmodm_1_1can_1_1_message.html", "structmodm_1_1can_1_1_message" ]
      ] ],
      [ "chrono", null, [
        [ "milli_clock", "structmodm_1_1chrono_1_1milli__clock.html", null ],
        [ "micro_clock", "structmodm_1_1chrono_1_1micro__clock.html", null ]
      ] ],
      [ "log", "namespacemodm_1_1log.html", [
        [ "Logger", "classmodm_1_1log_1_1_logger.html", null ],
        [ "DefaultStyle", "classmodm_1_1log_1_1_default_style.html", "classmodm_1_1log_1_1_default_style" ],
        [ "Style", "classmodm_1_1log_1_1_style.html", "classmodm_1_1log_1_1_style" ],
        [ "Prefix", "classmodm_1_1log_1_1_prefix.html", "classmodm_1_1log_1_1_prefix" ],
        [ "StdColour", "classmodm_1_1log_1_1_std_colour.html", "classmodm_1_1log_1_1_std_colour" ],
        [ "StyleWrapper", "classmodm_1_1log_1_1_style_wrapper.html", "classmodm_1_1log_1_1_style_wrapper" ]
      ] ],
      [ "filter", "namespacemodm_1_1filter.html", [
        [ "Debounce", "classmodm_1_1filter_1_1_debounce.html", "classmodm_1_1filter_1_1_debounce" ],
        [ "Fir", "classmodm_1_1filter_1_1_fir.html", "classmodm_1_1filter_1_1_fir" ],
        [ "Median", "classmodm_1_1filter_1_1_median.html", "classmodm_1_1filter_1_1_median" ],
        [ "Median&lt; T, 3 &gt;", "classmodm_1_1filter_1_1_median_3_01_t_00_013_01_4.html", "classmodm_1_1filter_1_1_median_3_01_t_00_013_01_4" ],
        [ "Median&lt; T, 5 &gt;", "classmodm_1_1filter_1_1_median_3_01_t_00_015_01_4.html", "classmodm_1_1filter_1_1_median_3_01_t_00_015_01_4" ],
        [ "Median&lt; T, 7 &gt;", "classmodm_1_1filter_1_1_median_3_01_t_00_017_01_4.html", "classmodm_1_1filter_1_1_median_3_01_t_00_017_01_4" ],
        [ "Median&lt; T, 9 &gt;", "classmodm_1_1filter_1_1_median_3_01_t_00_019_01_4.html", "classmodm_1_1filter_1_1_median_3_01_t_00_019_01_4" ],
        [ "MovingAverage", "classmodm_1_1filter_1_1_moving_average.html", "classmodm_1_1filter_1_1_moving_average" ],
        [ "MovingAverage&lt; double, N &gt;", "classmodm_1_1filter_1_1_moving_average_3_01double_00_01_n_01_4.html", "classmodm_1_1filter_1_1_moving_average_3_01double_00_01_n_01_4" ],
        [ "Ramp", "classmodm_1_1filter_1_1_ramp.html", "classmodm_1_1filter_1_1_ramp" ]
      ] ],
      [ "interpolation", null, [
        [ "Lagrange", "classmodm_1_1interpolation_1_1_lagrange.html", "classmodm_1_1interpolation_1_1_lagrange" ],
        [ "Linear", "classmodm_1_1interpolation_1_1_linear.html", "classmodm_1_1interpolation_1_1_linear" ]
      ] ],
      [ "platform", null, [
        [ "Adc1", "classmodm_1_1platform_1_1_adc1.html", "classmodm_1_1platform_1_1_adc1" ],
        [ "Adc3", "classmodm_1_1platform_1_1_adc3.html", "classmodm_1_1platform_1_1_adc3" ],
        [ "AdcInterrupt1", "classmodm_1_1platform_1_1_adc_interrupt1.html", null ],
        [ "AdcInterrupt3", "classmodm_1_1platform_1_1_adc_interrupt3.html", null ],
        [ "Can1", "classmodm_1_1platform_1_1_can1.html", null ],
        [ "Can2", "classmodm_1_1platform_1_1_can2.html", null ],
        [ "CanFilter", "classmodm_1_1platform_1_1_can_filter.html", "classmodm_1_1platform_1_1_can_filter" ],
        [ "Rcc", "classmodm_1_1platform_1_1_rcc.html", "classmodm_1_1platform_1_1_rcc" ],
        [ "SysTickTimer", "classmodm_1_1platform_1_1_sys_tick_timer.html", null ],
        [ "HeapTable", "classmodm_1_1platform_1_1_heap_table.html", null ],
        [ "Flash", "classmodm_1_1platform_1_1_flash.html", null ],
        [ "Gpio", "structmodm_1_1platform_1_1_gpio.html", "structmodm_1_1platform_1_1_gpio" ],
        [ "GpioA0", "classmodm_1_1platform_1_1_gpio_a0.html", null ],
        [ "GpioA1", "classmodm_1_1platform_1_1_gpio_a1.html", null ],
        [ "GpioA10", "classmodm_1_1platform_1_1_gpio_a10.html", null ],
        [ "GpioA11", "classmodm_1_1platform_1_1_gpio_a11.html", null ],
        [ "GpioA12", "classmodm_1_1platform_1_1_gpio_a12.html", null ],
        [ "GpioA13", "classmodm_1_1platform_1_1_gpio_a13.html", null ],
        [ "GpioA14", "classmodm_1_1platform_1_1_gpio_a14.html", null ],
        [ "GpioA15", "classmodm_1_1platform_1_1_gpio_a15.html", null ],
        [ "GpioA2", "classmodm_1_1platform_1_1_gpio_a2.html", null ],
        [ "GpioA3", "classmodm_1_1platform_1_1_gpio_a3.html", null ],
        [ "GpioA4", "classmodm_1_1platform_1_1_gpio_a4.html", null ],
        [ "GpioA5", "classmodm_1_1platform_1_1_gpio_a5.html", null ],
        [ "GpioA6", "classmodm_1_1platform_1_1_gpio_a6.html", null ],
        [ "GpioA7", "classmodm_1_1platform_1_1_gpio_a7.html", null ],
        [ "GpioA8", "classmodm_1_1platform_1_1_gpio_a8.html", null ],
        [ "GpioA9", "classmodm_1_1platform_1_1_gpio_a9.html", null ],
        [ "GpioB0", "classmodm_1_1platform_1_1_gpio_b0.html", null ],
        [ "GpioB1", "classmodm_1_1platform_1_1_gpio_b1.html", null ],
        [ "GpioB10", "classmodm_1_1platform_1_1_gpio_b10.html", null ],
        [ "GpioB11", "classmodm_1_1platform_1_1_gpio_b11.html", null ],
        [ "GpioB12", "classmodm_1_1platform_1_1_gpio_b12.html", null ],
        [ "GpioB13", "classmodm_1_1platform_1_1_gpio_b13.html", null ],
        [ "GpioB14", "classmodm_1_1platform_1_1_gpio_b14.html", null ],
        [ "GpioB15", "classmodm_1_1platform_1_1_gpio_b15.html", null ],
        [ "GpioB2", "classmodm_1_1platform_1_1_gpio_b2.html", null ],
        [ "GpioB3", "classmodm_1_1platform_1_1_gpio_b3.html", null ],
        [ "GpioB4", "classmodm_1_1platform_1_1_gpio_b4.html", null ],
        [ "GpioB5", "classmodm_1_1platform_1_1_gpio_b5.html", null ],
        [ "GpioB6", "classmodm_1_1platform_1_1_gpio_b6.html", null ],
        [ "GpioB7", "classmodm_1_1platform_1_1_gpio_b7.html", null ],
        [ "GpioB8", "classmodm_1_1platform_1_1_gpio_b8.html", null ],
        [ "GpioB9", "classmodm_1_1platform_1_1_gpio_b9.html", null ],
        [ "GpioC0", "classmodm_1_1platform_1_1_gpio_c0.html", null ],
        [ "GpioC1", "classmodm_1_1platform_1_1_gpio_c1.html", null ],
        [ "GpioC10", "classmodm_1_1platform_1_1_gpio_c10.html", null ],
        [ "GpioC11", "classmodm_1_1platform_1_1_gpio_c11.html", null ],
        [ "GpioC12", "classmodm_1_1platform_1_1_gpio_c12.html", null ],
        [ "GpioC13", "classmodm_1_1platform_1_1_gpio_c13.html", null ],
        [ "GpioC14", "classmodm_1_1platform_1_1_gpio_c14.html", null ],
        [ "GpioC15", "classmodm_1_1platform_1_1_gpio_c15.html", null ],
        [ "GpioC2", "classmodm_1_1platform_1_1_gpio_c2.html", null ],
        [ "GpioC3", "classmodm_1_1platform_1_1_gpio_c3.html", null ],
        [ "GpioC4", "classmodm_1_1platform_1_1_gpio_c4.html", null ],
        [ "GpioC5", "classmodm_1_1platform_1_1_gpio_c5.html", null ],
        [ "GpioC6", "classmodm_1_1platform_1_1_gpio_c6.html", null ],
        [ "GpioC7", "classmodm_1_1platform_1_1_gpio_c7.html", null ],
        [ "GpioC8", "classmodm_1_1platform_1_1_gpio_c8.html", null ],
        [ "GpioC9", "classmodm_1_1platform_1_1_gpio_c9.html", null ],
        [ "GpioD0", "classmodm_1_1platform_1_1_gpio_d0.html", null ],
        [ "GpioD1", "classmodm_1_1platform_1_1_gpio_d1.html", null ],
        [ "GpioD10", "classmodm_1_1platform_1_1_gpio_d10.html", null ],
        [ "GpioD11", "classmodm_1_1platform_1_1_gpio_d11.html", null ],
        [ "GpioD12", "classmodm_1_1platform_1_1_gpio_d12.html", null ],
        [ "GpioD13", "classmodm_1_1platform_1_1_gpio_d13.html", null ],
        [ "GpioD14", "classmodm_1_1platform_1_1_gpio_d14.html", null ],
        [ "GpioD15", "classmodm_1_1platform_1_1_gpio_d15.html", null ],
        [ "GpioD2", "classmodm_1_1platform_1_1_gpio_d2.html", null ],
        [ "GpioD3", "classmodm_1_1platform_1_1_gpio_d3.html", null ],
        [ "GpioD4", "classmodm_1_1platform_1_1_gpio_d4.html", null ],
        [ "GpioD5", "classmodm_1_1platform_1_1_gpio_d5.html", null ],
        [ "GpioD6", "classmodm_1_1platform_1_1_gpio_d6.html", null ],
        [ "GpioD7", "classmodm_1_1platform_1_1_gpio_d7.html", null ],
        [ "GpioD8", "classmodm_1_1platform_1_1_gpio_d8.html", null ],
        [ "GpioD9", "classmodm_1_1platform_1_1_gpio_d9.html", null ],
        [ "GpioE0", "classmodm_1_1platform_1_1_gpio_e0.html", null ],
        [ "GpioE1", "classmodm_1_1platform_1_1_gpio_e1.html", null ],
        [ "GpioE10", "classmodm_1_1platform_1_1_gpio_e10.html", null ],
        [ "GpioE11", "classmodm_1_1platform_1_1_gpio_e11.html", null ],
        [ "GpioE12", "classmodm_1_1platform_1_1_gpio_e12.html", null ],
        [ "GpioE13", "classmodm_1_1platform_1_1_gpio_e13.html", null ],
        [ "GpioE14", "classmodm_1_1platform_1_1_gpio_e14.html", null ],
        [ "GpioE15", "classmodm_1_1platform_1_1_gpio_e15.html", null ],
        [ "GpioE2", "classmodm_1_1platform_1_1_gpio_e2.html", null ],
        [ "GpioE3", "classmodm_1_1platform_1_1_gpio_e3.html", null ],
        [ "GpioE4", "classmodm_1_1platform_1_1_gpio_e4.html", null ],
        [ "GpioE5", "classmodm_1_1platform_1_1_gpio_e5.html", null ],
        [ "GpioE6", "classmodm_1_1platform_1_1_gpio_e6.html", null ],
        [ "GpioE7", "classmodm_1_1platform_1_1_gpio_e7.html", null ],
        [ "GpioE8", "classmodm_1_1platform_1_1_gpio_e8.html", null ],
        [ "GpioE9", "classmodm_1_1platform_1_1_gpio_e9.html", null ],
        [ "GpioF0", "classmodm_1_1platform_1_1_gpio_f0.html", null ],
        [ "GpioF1", "classmodm_1_1platform_1_1_gpio_f1.html", null ],
        [ "GpioF10", "classmodm_1_1platform_1_1_gpio_f10.html", null ],
        [ "GpioF11", "classmodm_1_1platform_1_1_gpio_f11.html", null ],
        [ "GpioF12", "classmodm_1_1platform_1_1_gpio_f12.html", null ],
        [ "GpioF13", "classmodm_1_1platform_1_1_gpio_f13.html", null ],
        [ "GpioF14", "classmodm_1_1platform_1_1_gpio_f14.html", null ],
        [ "GpioF15", "classmodm_1_1platform_1_1_gpio_f15.html", null ],
        [ "GpioF2", "classmodm_1_1platform_1_1_gpio_f2.html", null ],
        [ "GpioF3", "classmodm_1_1platform_1_1_gpio_f3.html", null ],
        [ "GpioF4", "classmodm_1_1platform_1_1_gpio_f4.html", null ],
        [ "GpioF5", "classmodm_1_1platform_1_1_gpio_f5.html", null ],
        [ "GpioF6", "classmodm_1_1platform_1_1_gpio_f6.html", null ],
        [ "GpioF7", "classmodm_1_1platform_1_1_gpio_f7.html", null ],
        [ "GpioF8", "classmodm_1_1platform_1_1_gpio_f8.html", null ],
        [ "GpioF9", "classmodm_1_1platform_1_1_gpio_f9.html", null ],
        [ "GpioG0", "classmodm_1_1platform_1_1_gpio_g0.html", null ],
        [ "GpioG1", "classmodm_1_1platform_1_1_gpio_g1.html", null ],
        [ "GpioG10", "classmodm_1_1platform_1_1_gpio_g10.html", null ],
        [ "GpioG11", "classmodm_1_1platform_1_1_gpio_g11.html", null ],
        [ "GpioG12", "classmodm_1_1platform_1_1_gpio_g12.html", null ],
        [ "GpioG13", "classmodm_1_1platform_1_1_gpio_g13.html", null ],
        [ "GpioG14", "classmodm_1_1platform_1_1_gpio_g14.html", null ],
        [ "GpioG15", "classmodm_1_1platform_1_1_gpio_g15.html", null ],
        [ "GpioG2", "classmodm_1_1platform_1_1_gpio_g2.html", null ],
        [ "GpioG3", "classmodm_1_1platform_1_1_gpio_g3.html", null ],
        [ "GpioG4", "classmodm_1_1platform_1_1_gpio_g4.html", null ],
        [ "GpioG5", "classmodm_1_1platform_1_1_gpio_g5.html", null ],
        [ "GpioG6", "classmodm_1_1platform_1_1_gpio_g6.html", null ],
        [ "GpioG7", "classmodm_1_1platform_1_1_gpio_g7.html", null ],
        [ "GpioG8", "classmodm_1_1platform_1_1_gpio_g8.html", null ],
        [ "GpioG9", "classmodm_1_1platform_1_1_gpio_g9.html", null ],
        [ "GpioH0", "classmodm_1_1platform_1_1_gpio_h0.html", null ],
        [ "GpioH1", "classmodm_1_1platform_1_1_gpio_h1.html", null ],
        [ "GpioH10", "classmodm_1_1platform_1_1_gpio_h10.html", null ],
        [ "GpioH11", "classmodm_1_1platform_1_1_gpio_h11.html", null ],
        [ "GpioH12", "classmodm_1_1platform_1_1_gpio_h12.html", null ],
        [ "GpioH13", "classmodm_1_1platform_1_1_gpio_h13.html", null ],
        [ "GpioH14", "classmodm_1_1platform_1_1_gpio_h14.html", null ],
        [ "GpioH15", "classmodm_1_1platform_1_1_gpio_h15.html", null ],
        [ "GpioH2", "classmodm_1_1platform_1_1_gpio_h2.html", null ],
        [ "GpioH3", "classmodm_1_1platform_1_1_gpio_h3.html", null ],
        [ "GpioH4", "classmodm_1_1platform_1_1_gpio_h4.html", null ],
        [ "GpioH5", "classmodm_1_1platform_1_1_gpio_h5.html", null ],
        [ "GpioH6", "classmodm_1_1platform_1_1_gpio_h6.html", null ],
        [ "GpioH7", "classmodm_1_1platform_1_1_gpio_h7.html", null ],
        [ "GpioH8", "classmodm_1_1platform_1_1_gpio_h8.html", null ],
        [ "GpioH9", "classmodm_1_1platform_1_1_gpio_h9.html", null ],
        [ "GpioI0", "classmodm_1_1platform_1_1_gpio_i0.html", null ],
        [ "GpioI1", "classmodm_1_1platform_1_1_gpio_i1.html", null ],
        [ "GpioI10", "classmodm_1_1platform_1_1_gpio_i10.html", null ],
        [ "GpioI11", "classmodm_1_1platform_1_1_gpio_i11.html", null ],
        [ "GpioI2", "classmodm_1_1platform_1_1_gpio_i2.html", null ],
        [ "GpioI3", "classmodm_1_1platform_1_1_gpio_i3.html", null ],
        [ "GpioI4", "classmodm_1_1platform_1_1_gpio_i4.html", null ],
        [ "GpioI5", "classmodm_1_1platform_1_1_gpio_i5.html", null ],
        [ "GpioI6", "classmodm_1_1platform_1_1_gpio_i6.html", null ],
        [ "GpioI7", "classmodm_1_1platform_1_1_gpio_i7.html", null ],
        [ "GpioI8", "classmodm_1_1platform_1_1_gpio_i8.html", null ],
        [ "GpioI9", "classmodm_1_1platform_1_1_gpio_i9.html", null ],
        [ "GpioInverted", "classmodm_1_1platform_1_1_gpio_inverted.html", null ],
        [ "GpioPort", "classmodm_1_1platform_1_1_gpio_port.html", null ],
        [ "GpioSet", "classmodm_1_1platform_1_1_gpio_set.html", null ],
        [ "SoftwareGpioPort", "classmodm_1_1platform_1_1_software_gpio_port.html", null ],
        [ "GpioUnused", "classmodm_1_1platform_1_1_gpio_unused.html", null ],
        [ "I2cMaster3", "classmodm_1_1platform_1_1_i2c_master3.html", null ],
        [ "RandomNumberGenerator", "classmodm_1_1platform_1_1_random_number_generator.html", null ],
        [ "SpiBase", "classmodm_1_1platform_1_1_spi_base.html", "classmodm_1_1platform_1_1_spi_base" ],
        [ "SpiHal1", "classmodm_1_1platform_1_1_spi_hal1.html", null ],
        [ "SpiHal2", "classmodm_1_1platform_1_1_spi_hal2.html", null ],
        [ "SpiMaster1", "classmodm_1_1platform_1_1_spi_master1.html", "classmodm_1_1platform_1_1_spi_master1" ],
        [ "SpiMaster2", "classmodm_1_1platform_1_1_spi_master2.html", "classmodm_1_1platform_1_1_spi_master2" ],
        [ "AdvancedControlTimer", "classmodm_1_1platform_1_1_advanced_control_timer.html", "classmodm_1_1platform_1_1_advanced_control_timer" ],
        [ "BasicTimer", "classmodm_1_1platform_1_1_basic_timer.html", null ],
        [ "GeneralPurposeTimer", "classmodm_1_1platform_1_1_general_purpose_timer.html", "classmodm_1_1platform_1_1_general_purpose_timer" ],
        [ "Timer1", "classmodm_1_1platform_1_1_timer1.html", null ],
        [ "Timer10", "classmodm_1_1platform_1_1_timer10.html", "classmodm_1_1platform_1_1_timer10" ],
        [ "Timer4", "classmodm_1_1platform_1_1_timer4.html", "classmodm_1_1platform_1_1_timer4" ],
        [ "Timer8", "classmodm_1_1platform_1_1_timer8.html", null ],
        [ "Usart1", "classmodm_1_1platform_1_1_usart1.html", null ],
        [ "Usart3", "classmodm_1_1platform_1_1_usart3.html", null ],
        [ "Usart6", "classmodm_1_1platform_1_1_usart6.html", null ],
        [ "UartBase", "classmodm_1_1platform_1_1_uart_base.html", "classmodm_1_1platform_1_1_uart_base" ],
        [ "UsartHal1", "classmodm_1_1platform_1_1_usart_hal1.html", null ],
        [ "UsartHal3", "classmodm_1_1platform_1_1_usart_hal3.html", null ],
        [ "UsartHal6", "classmodm_1_1platform_1_1_usart_hal6.html", null ]
      ] ],
      [ "cortex", null, [
        [ "SysTickTimer", "classmodm_1_1cortex_1_1_sys_tick_timer.html", null ]
      ] ],
      [ "pt", null, [
        [ "Protothread", "classmodm_1_1pt_1_1_protothread.html", "classmodm_1_1pt_1_1_protothread" ],
        [ "Semaphore", "classmodm_1_1pt_1_1_semaphore.html", "classmodm_1_1pt_1_1_semaphore" ]
      ] ],
      [ "allocator", null, [
        [ "AllocatorBase", "classmodm_1_1allocator_1_1_allocator_base.html", null ],
        [ "Block", "classmodm_1_1allocator_1_1_block.html", "classmodm_1_1allocator_1_1_block" ],
        [ "Dynamic", "classmodm_1_1allocator_1_1_dynamic.html", "classmodm_1_1allocator_1_1_dynamic" ],
        [ "Static", "classmodm_1_1allocator_1_1_static.html", "classmodm_1_1allocator_1_1_static" ]
      ] ],
      [ "detail", null, [
        [ "MakeSigned&lt; Vector&lt; T, N &gt; &gt;", "structmodm_1_1detail_1_1_make_signed_3_01_vector_3_01_t_00_01_n_01_4_01_4.html", null ],
        [ "MakeUnsigned&lt; Vector&lt; T, N &gt; &gt;", "structmodm_1_1detail_1_1_make_unsigned_3_01_vector_3_01_t_00_01_n_01_4_01_4.html", null ],
        [ "WideType&lt; Vector&lt; T, N &gt; &gt;", "structmodm_1_1detail_1_1_wide_type_3_01_vector_3_01_t_00_01_n_01_4_01_4.html", null ]
      ] ],
      [ "Adc", "classmodm_1_1_adc.html", null ],
      [ "AdcInterrupt", "classmodm_1_1_adc_interrupt.html", null ],
      [ "AssertionInfo", "structmodm_1_1_assertion_info.html", "structmodm_1_1_assertion_info" ],
      [ "Can", "classmodm_1_1_can.html", "classmodm_1_1_can" ],
      [ "Gpio", "structmodm_1_1_gpio.html", "structmodm_1_1_gpio" ],
      [ "GpioInput", "classmodm_1_1_gpio_input.html", null ],
      [ "GpioOutput", "classmodm_1_1_gpio_output.html", null ],
      [ "GpioIO", "classmodm_1_1_gpio_i_o.html", null ],
      [ "GpioPort", "classmodm_1_1_gpio_port.html", "classmodm_1_1_gpio_port" ],
      [ "I2c", "structmodm_1_1_i2c.html", "structmodm_1_1_i2c" ],
      [ "I2cDevice", "classmodm_1_1_i2c_device.html", "classmodm_1_1_i2c_device" ],
      [ "I2cMaster", "classmodm_1_1_i2c_master.html", "classmodm_1_1_i2c_master" ],
      [ "I2cTransaction", "classmodm_1_1_i2c_transaction.html", "classmodm_1_1_i2c_transaction" ],
      [ "I2cWriteReadTransaction", "classmodm_1_1_i2c_write_read_transaction.html", "classmodm_1_1_i2c_write_read_transaction" ],
      [ "I2cWriteTransaction", "classmodm_1_1_i2c_write_transaction.html", "classmodm_1_1_i2c_write_transaction" ],
      [ "I2cReadTransaction", "classmodm_1_1_i2c_read_transaction.html", "classmodm_1_1_i2c_read_transaction" ],
      [ "PeripheralDriver", "classmodm_1_1_peripheral_driver.html", null ],
      [ "Register", "structmodm_1_1_register.html", "structmodm_1_1_register" ],
      [ "FlagsOperators", "structmodm_1_1_flags_operators.html", "structmodm_1_1_flags_operators" ],
      [ "Flags", "structmodm_1_1_flags.html", "structmodm_1_1_flags" ],
      [ "FlagsGroup&lt; T &gt;", "structmodm_1_1_flags_group_3_01_t_01_4.html", "structmodm_1_1_flags_group_3_01_t_01_4" ],
      [ "Configuration", "structmodm_1_1_configuration.html", "structmodm_1_1_configuration" ],
      [ "Value", "structmodm_1_1_value.html", "structmodm_1_1_value" ],
      [ "Spi", "structmodm_1_1_spi.html", "structmodm_1_1_spi" ],
      [ "SpiDevice", "classmodm_1_1_spi_device.html", null ],
      [ "SpiMaster", "classmodm_1_1_spi_master.html", null ],
      [ "Uart", "classmodm_1_1_uart.html", null ],
      [ "BoundedDeque", "classmodm_1_1_bounded_deque.html", "classmodm_1_1_bounded_deque" ],
      [ "DoublyLinkedList", "classmodm_1_1_doubly_linked_list.html", "classmodm_1_1_doubly_linked_list" ],
      [ "DynamicArray", "classmodm_1_1_dynamic_array.html", "classmodm_1_1_dynamic_array" ],
      [ "LinkedList", "classmodm_1_1_linked_list.html", "classmodm_1_1_linked_list" ],
      [ "Pair", "classmodm_1_1_pair.html", null ],
      [ "Queue", "classmodm_1_1_queue.html", "classmodm_1_1_queue" ],
      [ "BoundedQueue", "classmodm_1_1_bounded_queue.html", null ],
      [ "SmartPointer", "classmodm_1_1_smart_pointer.html", "classmodm_1_1_smart_pointer" ],
      [ "Stack", "classmodm_1_1_stack.html", null ],
      [ "BoundedStack", "classmodm_1_1_bounded_stack.html", null ],
      [ "Bno055", "classmodm_1_1_bno055.html", "classmodm_1_1_bno055" ],
      [ "bno055", "structmodm_1_1bno055.html", "structmodm_1_1bno055" ],
      [ "IODevice", "classmodm_1_1_i_o_device.html", "classmodm_1_1_i_o_device" ],
      [ "IODeviceWrapper", "classmodm_1_1_i_o_device_wrapper.html", "classmodm_1_1_i_o_device_wrapper" ],
      [ "IODeviceObjectWrapper", "classmodm_1_1_i_o_device_object_wrapper.html", "classmodm_1_1_i_o_device_object_wrapper" ],
      [ "IOStream", "classmodm_1_1_i_o_stream.html", "classmodm_1_1_i_o_stream" ],
      [ "GenericPrescaler", "classmodm_1_1_generic_prescaler.html", "classmodm_1_1_generic_prescaler" ],
      [ "Pid", "classmodm_1_1_pid.html", "classmodm_1_1_pid" ],
      [ "SCurveController", "classmodm_1_1_s_curve_controller.html", "classmodm_1_1_s_curve_controller" ],
      [ "SCurveGenerator", "classmodm_1_1_s_curve_generator.html", null ],
      [ "Angle", "classmodm_1_1_angle.html", null ],
      [ "Line2D", "classmodm_1_1_line2_d.html", "classmodm_1_1_line2_d" ],
      [ "LineSegment2D", "classmodm_1_1_line_segment2_d.html", "classmodm_1_1_line_segment2_d" ],
      [ "Polygon2D", "classmodm_1_1_polygon2_d.html", "classmodm_1_1_polygon2_d" ],
      [ "Circle2D", "classmodm_1_1_circle2_d.html", "classmodm_1_1_circle2_d" ],
      [ "GeometricTraits", "structmodm_1_1_geometric_traits.html", null ],
      [ "GeometricTraits&lt; int8_t &gt;", "structmodm_1_1_geometric_traits_3_01int8__t_01_4.html", null ],
      [ "GeometricTraits&lt; uint8_t &gt;", "structmodm_1_1_geometric_traits_3_01uint8__t_01_4.html", null ],
      [ "GeometricTraits&lt; int16_t &gt;", "structmodm_1_1_geometric_traits_3_01int16__t_01_4.html", null ],
      [ "GeometricTraits&lt; int32_t &gt;", "structmodm_1_1_geometric_traits_3_01int32__t_01_4.html", null ],
      [ "GeometricTraits&lt; float &gt;", "structmodm_1_1_geometric_traits_3_01float_01_4.html", null ],
      [ "GeometricTraits&lt; double &gt;", "structmodm_1_1_geometric_traits_3_01double_01_4.html", null ],
      [ "Location2D", "classmodm_1_1_location2_d.html", "classmodm_1_1_location2_d" ],
      [ "PointSet2D", "classmodm_1_1_point_set2_d.html", "classmodm_1_1_point_set2_d" ],
      [ "Ray2D", "classmodm_1_1_ray2_d.html", "classmodm_1_1_ray2_d" ],
      [ "Vector", "classmodm_1_1_vector.html", null ],
      [ "Matrix", "classmodm_1_1_matrix.html", "classmodm_1_1_matrix" ],
      [ "Quaternion", "classmodm_1_1_quaternion.html", "classmodm_1_1_quaternion" ],
      [ "Vector&lt; T, 1 &gt;", "classmodm_1_1_vector_3_01_t_00_011_01_4.html", null ],
      [ "Vector&lt; T, 2 &gt;", "classmodm_1_1_vector_3_01_t_00_012_01_4.html", "classmodm_1_1_vector_3_01_t_00_012_01_4" ],
      [ "Vector&lt; T, 3 &gt;", "classmodm_1_1_vector_3_01_t_00_013_01_4.html", null ],
      [ "Vector&lt; T, 4 &gt;", "classmodm_1_1_vector_3_01_t_00_014_01_4.html", null ],
      [ "LUDecomposition", "classmodm_1_1_l_u_decomposition.html", null ],
      [ "Saturated", "classmodm_1_1_saturated.html", "classmodm_1_1_saturated" ],
      [ "Tolerance", "classmodm_1_1_tolerance.html", null ],
      [ "CanBitTimingConfiguration", "structmodm_1_1_can_bit_timing_configuration.html", null ],
      [ "CanBitTiming", "classmodm_1_1_can_bit_timing.html", null ],
      [ "NestedResumable", "classmodm_1_1_nested_resumable.html", "classmodm_1_1_nested_resumable" ],
      [ "ResumableResult", "structmodm_1_1_resumable_result.html", "structmodm_1_1_resumable_result" ],
      [ "Resumable", "classmodm_1_1_resumable.html", "classmodm_1_1_resumable" ],
      [ "Task", "classmodm_1_1_task.html", null ],
      [ "GenericPeriodicTimer", "classmodm_1_1_generic_periodic_timer.html", "classmodm_1_1_generic_periodic_timer" ],
      [ "GenericTimeout", "classmodm_1_1_generic_timeout.html", "classmodm_1_1_generic_timeout" ],
      [ "aligned_storage", "structmodm_1_1aligned__storage.html", null ],
      [ "inplace_any", "classmodm_1_1inplace__any.html", "classmodm_1_1inplace__any" ],
      [ "get_callable_signature", "structmodm_1_1get__callable__signature.html", null ],
      [ "get_callable_signature&lt; R(*)(Args...)&gt;", "structmodm_1_1get__callable__signature_3_01_r_07_5_08_07_args_8_8_8_08_4.html", null ],
      [ "get_callable_signature&lt; R(Args...)&gt;", "structmodm_1_1get__callable__signature_3_01_r_07_args_8_8_8_08_4.html", null ],
      [ "get_callable_signature&lt; F &gt;", "structmodm_1_1get__callable__signature_3_01_f_01_4.html", null ]
    ] ],
    [ "mem_pool_t", "structmem__pool__t.html", null ],
    [ "RxMessage", "struct_rx_message.html", null ],
    [ "table_pool_t", "structtable__pool__t.html", null ]
];