var hierarchy =
[
    [ "modm::aligned_storage&lt; Cap, Align &gt;", "structmodm_1_1aligned__storage.html", null ],
    [ "modm::allocator::AllocatorBase&lt; T &gt;", "classmodm_1_1allocator_1_1_allocator_base.html", [
      [ "modm::allocator::Block< U, BLOCKSIZE >", "classmodm_1_1allocator_1_1_block.html", null ],
      [ "modm::allocator::Dynamic< U >", "classmodm_1_1allocator_1_1_dynamic.html", null ],
      [ "modm::allocator::Static< U, N >", "classmodm_1_1allocator_1_1_static.html", null ],
      [ "modm::allocator::Block< T, BLOCKSIZE >", "classmodm_1_1allocator_1_1_block.html", null ],
      [ "modm::allocator::Dynamic< T >", "classmodm_1_1allocator_1_1_dynamic.html", null ],
      [ "modm::allocator::Static< T, N >", "classmodm_1_1allocator_1_1_static.html", null ]
    ] ],
    [ "modm::Angle", "classmodm_1_1_angle.html", null ],
    [ "modm::AssertionInfo", "structmodm_1_1_assertion_info.html", null ],
    [ "modm::platform::BasicTimer", "classmodm_1_1platform_1_1_basic_timer.html", [
      [ "modm::platform::GeneralPurposeTimer", "classmodm_1_1platform_1_1_general_purpose_timer.html", [
        [ "modm::platform::AdvancedControlTimer", "classmodm_1_1platform_1_1_advanced_control_timer.html", [
          [ "modm::platform::Timer1", "classmodm_1_1platform_1_1_timer1.html", null ],
          [ "modm::platform::Timer8", "classmodm_1_1platform_1_1_timer8.html", null ]
        ] ],
        [ "modm::platform::Timer10", "classmodm_1_1platform_1_1_timer10.html", null ],
        [ "modm::platform::Timer4", "classmodm_1_1platform_1_1_timer4.html", null ]
      ] ]
    ] ],
    [ "modm::bno055", "structmodm_1_1bno055.html", [
      [ "modm::Bno055< I2cMaster >", "classmodm_1_1_bno055.html", null ]
    ] ],
    [ "modm::BoundedDeque&lt; T, N &gt;", "classmodm_1_1_bounded_deque.html", null ],
    [ "modm::CanBitTiming&lt; Clk, Bitrate, prescaler_width, bs1_width, bs2_width, sjw_width &gt;", "classmodm_1_1_can_bit_timing.html", null ],
    [ "modm::CanBitTimingConfiguration", "structmodm_1_1_can_bit_timing_configuration.html", null ],
    [ "modm::platform::CanFilter", "classmodm_1_1platform_1_1_can_filter.html", null ],
    [ "modm::Circle2D&lt; T &gt;", "classmodm_1_1_circle2_d.html", null ],
    [ "modm::atomic::Container&lt; T &gt;", "classmodm_1_1atomic_1_1_container.html", null ],
    [ "modm::bno055::Data", "structmodm_1_1bno055_1_1_data.html", null ],
    [ "modm::filter::Debounce&lt; T &gt;", "classmodm_1_1filter_1_1_debounce.html", null ],
    [ "modm::log::DefaultStyle", "classmodm_1_1log_1_1_default_style.html", null ],
    [ "modm::DoublyLinkedList&lt; T, Allocator &gt;", "classmodm_1_1_doubly_linked_list.html", null ],
    [ "modm::DynamicArray&lt; T, Allocator &gt;", "classmodm_1_1_dynamic_array.html", null ],
    [ "modm::platform::CanFilter::ExtendedFilterMask", "structmodm_1_1platform_1_1_can_filter_1_1_extended_filter_mask.html", null ],
    [ "modm::platform::CanFilter::ExtendedFilterMaskShort", "structmodm_1_1platform_1_1_can_filter_1_1_extended_filter_mask_short.html", null ],
    [ "modm::can::ExtendedIdentifier", "structmodm_1_1can_1_1_extended_identifier.html", null ],
    [ "modm::platform::CanFilter::ExtendedIdentifier", "structmodm_1_1platform_1_1_can_filter_1_1_extended_identifier.html", null ],
    [ "modm::platform::CanFilter::ExtendedIdentifierShort", "structmodm_1_1platform_1_1_can_filter_1_1_extended_identifier_short.html", null ],
    [ "modm::can::ExtendedMask", "structmodm_1_1can_1_1_extended_mask.html", null ],
    [ "modm::filter::Fir&lt; T, N, BLOCK_SIZE, ScaleFactor &gt;", "classmodm_1_1filter_1_1_fir.html", null ],
    [ "modm::atomic::Flag", "classmodm_1_1atomic_1_1_flag.html", null ],
    [ "modm::can::Message::Flags", "structmodm_1_1can_1_1_message_1_1_flags.html", null ],
    [ "modm::accessor::Flash&lt; T &gt;", "classmodm_1_1accessor_1_1_flash.html", null ],
    [ "modm::platform::Flash", "classmodm_1_1platform_1_1_flash.html", null ],
    [ "modm::GenericPrescaler&lt; T &gt;", "classmodm_1_1_generic_prescaler.html", null ],
    [ "modm::GenericTimeout&lt; Clock, Duration &gt;", "classmodm_1_1_generic_timeout.html", [
      [ "modm::GenericPeriodicTimer< Clock, Duration >", "classmodm_1_1_generic_periodic_timer.html", null ]
    ] ],
    [ "modm::GenericTimeout&lt; Clock, ShortDuration &gt;", "classmodm_1_1_generic_timeout.html", [
      [ "modm::GenericPeriodicTimer< Clock, ShortDuration >", "classmodm_1_1_generic_periodic_timer.html", null ]
    ] ],
    [ "modm::GenericTimeout&lt; PreciseClock, PreciseDuration &gt;", "classmodm_1_1_generic_timeout.html", [
      [ "modm::GenericPeriodicTimer< PreciseClock, PreciseDuration >", "classmodm_1_1_generic_periodic_timer.html", null ]
    ] ],
    [ "modm::GenericTimeout&lt; PreciseClock, ShortPreciseDuration &gt;", "classmodm_1_1_generic_timeout.html", [
      [ "modm::GenericPeriodicTimer< PreciseClock, ShortPreciseDuration >", "classmodm_1_1_generic_periodic_timer.html", null ]
    ] ],
    [ "modm::GeometricTraits&lt; T &gt;", "structmodm_1_1_geometric_traits.html", null ],
    [ "modm::GeometricTraits&lt; double &gt;", "structmodm_1_1_geometric_traits_3_01double_01_4.html", null ],
    [ "modm::GeometricTraits&lt; float &gt;", "structmodm_1_1_geometric_traits_3_01float_01_4.html", null ],
    [ "modm::GeometricTraits&lt; int16_t &gt;", "structmodm_1_1_geometric_traits_3_01int16__t_01_4.html", null ],
    [ "modm::GeometricTraits&lt; int32_t &gt;", "structmodm_1_1_geometric_traits_3_01int32__t_01_4.html", null ],
    [ "modm::GeometricTraits&lt; int8_t &gt;", "structmodm_1_1_geometric_traits_3_01int8__t_01_4.html", null ],
    [ "modm::GeometricTraits&lt; uint8_t &gt;", "structmodm_1_1_geometric_traits_3_01uint8__t_01_4.html", null ],
    [ "modm::get_callable_signature&lt; F &gt;", "structmodm_1_1get__callable__signature.html", null ],
    [ "modm::get_callable_signature&lt; F &gt;", "structmodm_1_1get__callable__signature_3_01_f_01_4.html", null ],
    [ "modm::get_callable_signature&lt; R(*)(Args...)&gt;", "structmodm_1_1get__callable__signature_3_01_r_07_5_08_07_args_8_8_8_08_4.html", null ],
    [ "modm::get_callable_signature&lt; R(Args...)&gt;", "structmodm_1_1get__callable__signature_3_01_r_07_args_8_8_8_08_4.html", null ],
    [ "modm::Gpio", "structmodm_1_1_gpio.html", [
      [ "modm::GpioInput", "classmodm_1_1_gpio_input.html", [
        [ "modm::GpioIO", "classmodm_1_1_gpio_i_o.html", [
          [ "modm::platform::GpioA0", "classmodm_1_1platform_1_1_gpio_a0.html", null ],
          [ "modm::platform::GpioA1", "classmodm_1_1platform_1_1_gpio_a1.html", null ],
          [ "modm::platform::GpioA10", "classmodm_1_1platform_1_1_gpio_a10.html", null ],
          [ "modm::platform::GpioA11", "classmodm_1_1platform_1_1_gpio_a11.html", null ],
          [ "modm::platform::GpioA12", "classmodm_1_1platform_1_1_gpio_a12.html", null ],
          [ "modm::platform::GpioA13", "classmodm_1_1platform_1_1_gpio_a13.html", null ],
          [ "modm::platform::GpioA14", "classmodm_1_1platform_1_1_gpio_a14.html", null ],
          [ "modm::platform::GpioA15", "classmodm_1_1platform_1_1_gpio_a15.html", null ],
          [ "modm::platform::GpioA2", "classmodm_1_1platform_1_1_gpio_a2.html", null ],
          [ "modm::platform::GpioA3", "classmodm_1_1platform_1_1_gpio_a3.html", null ],
          [ "modm::platform::GpioA4", "classmodm_1_1platform_1_1_gpio_a4.html", null ],
          [ "modm::platform::GpioA5", "classmodm_1_1platform_1_1_gpio_a5.html", null ],
          [ "modm::platform::GpioA6", "classmodm_1_1platform_1_1_gpio_a6.html", null ],
          [ "modm::platform::GpioA7", "classmodm_1_1platform_1_1_gpio_a7.html", null ],
          [ "modm::platform::GpioA8", "classmodm_1_1platform_1_1_gpio_a8.html", null ],
          [ "modm::platform::GpioA9", "classmodm_1_1platform_1_1_gpio_a9.html", null ],
          [ "modm::platform::GpioB0", "classmodm_1_1platform_1_1_gpio_b0.html", null ],
          [ "modm::platform::GpioB1", "classmodm_1_1platform_1_1_gpio_b1.html", null ],
          [ "modm::platform::GpioB10", "classmodm_1_1platform_1_1_gpio_b10.html", null ],
          [ "modm::platform::GpioB11", "classmodm_1_1platform_1_1_gpio_b11.html", null ],
          [ "modm::platform::GpioB12", "classmodm_1_1platform_1_1_gpio_b12.html", null ],
          [ "modm::platform::GpioB13", "classmodm_1_1platform_1_1_gpio_b13.html", null ],
          [ "modm::platform::GpioB14", "classmodm_1_1platform_1_1_gpio_b14.html", null ],
          [ "modm::platform::GpioB15", "classmodm_1_1platform_1_1_gpio_b15.html", null ],
          [ "modm::platform::GpioB2", "classmodm_1_1platform_1_1_gpio_b2.html", null ],
          [ "modm::platform::GpioB3", "classmodm_1_1platform_1_1_gpio_b3.html", null ],
          [ "modm::platform::GpioB4", "classmodm_1_1platform_1_1_gpio_b4.html", null ],
          [ "modm::platform::GpioB5", "classmodm_1_1platform_1_1_gpio_b5.html", null ],
          [ "modm::platform::GpioB6", "classmodm_1_1platform_1_1_gpio_b6.html", null ],
          [ "modm::platform::GpioB7", "classmodm_1_1platform_1_1_gpio_b7.html", null ],
          [ "modm::platform::GpioB8", "classmodm_1_1platform_1_1_gpio_b8.html", null ],
          [ "modm::platform::GpioB9", "classmodm_1_1platform_1_1_gpio_b9.html", null ],
          [ "modm::platform::GpioC0", "classmodm_1_1platform_1_1_gpio_c0.html", null ],
          [ "modm::platform::GpioC1", "classmodm_1_1platform_1_1_gpio_c1.html", null ],
          [ "modm::platform::GpioC10", "classmodm_1_1platform_1_1_gpio_c10.html", null ],
          [ "modm::platform::GpioC11", "classmodm_1_1platform_1_1_gpio_c11.html", null ],
          [ "modm::platform::GpioC12", "classmodm_1_1platform_1_1_gpio_c12.html", null ],
          [ "modm::platform::GpioC13", "classmodm_1_1platform_1_1_gpio_c13.html", null ],
          [ "modm::platform::GpioC14", "classmodm_1_1platform_1_1_gpio_c14.html", null ],
          [ "modm::platform::GpioC15", "classmodm_1_1platform_1_1_gpio_c15.html", null ],
          [ "modm::platform::GpioC2", "classmodm_1_1platform_1_1_gpio_c2.html", null ],
          [ "modm::platform::GpioC3", "classmodm_1_1platform_1_1_gpio_c3.html", null ],
          [ "modm::platform::GpioC4", "classmodm_1_1platform_1_1_gpio_c4.html", null ],
          [ "modm::platform::GpioC5", "classmodm_1_1platform_1_1_gpio_c5.html", null ],
          [ "modm::platform::GpioC6", "classmodm_1_1platform_1_1_gpio_c6.html", null ],
          [ "modm::platform::GpioC7", "classmodm_1_1platform_1_1_gpio_c7.html", null ],
          [ "modm::platform::GpioC8", "classmodm_1_1platform_1_1_gpio_c8.html", null ],
          [ "modm::platform::GpioC9", "classmodm_1_1platform_1_1_gpio_c9.html", null ],
          [ "modm::platform::GpioD0", "classmodm_1_1platform_1_1_gpio_d0.html", null ],
          [ "modm::platform::GpioD1", "classmodm_1_1platform_1_1_gpio_d1.html", null ],
          [ "modm::platform::GpioD10", "classmodm_1_1platform_1_1_gpio_d10.html", null ],
          [ "modm::platform::GpioD11", "classmodm_1_1platform_1_1_gpio_d11.html", null ],
          [ "modm::platform::GpioD12", "classmodm_1_1platform_1_1_gpio_d12.html", null ],
          [ "modm::platform::GpioD13", "classmodm_1_1platform_1_1_gpio_d13.html", null ],
          [ "modm::platform::GpioD14", "classmodm_1_1platform_1_1_gpio_d14.html", null ],
          [ "modm::platform::GpioD15", "classmodm_1_1platform_1_1_gpio_d15.html", null ],
          [ "modm::platform::GpioD2", "classmodm_1_1platform_1_1_gpio_d2.html", null ],
          [ "modm::platform::GpioD3", "classmodm_1_1platform_1_1_gpio_d3.html", null ],
          [ "modm::platform::GpioD4", "classmodm_1_1platform_1_1_gpio_d4.html", null ],
          [ "modm::platform::GpioD5", "classmodm_1_1platform_1_1_gpio_d5.html", null ],
          [ "modm::platform::GpioD6", "classmodm_1_1platform_1_1_gpio_d6.html", null ],
          [ "modm::platform::GpioD7", "classmodm_1_1platform_1_1_gpio_d7.html", null ],
          [ "modm::platform::GpioD8", "classmodm_1_1platform_1_1_gpio_d8.html", null ],
          [ "modm::platform::GpioD9", "classmodm_1_1platform_1_1_gpio_d9.html", null ],
          [ "modm::platform::GpioE0", "classmodm_1_1platform_1_1_gpio_e0.html", null ],
          [ "modm::platform::GpioE1", "classmodm_1_1platform_1_1_gpio_e1.html", null ],
          [ "modm::platform::GpioE10", "classmodm_1_1platform_1_1_gpio_e10.html", null ],
          [ "modm::platform::GpioE11", "classmodm_1_1platform_1_1_gpio_e11.html", null ],
          [ "modm::platform::GpioE12", "classmodm_1_1platform_1_1_gpio_e12.html", null ],
          [ "modm::platform::GpioE13", "classmodm_1_1platform_1_1_gpio_e13.html", null ],
          [ "modm::platform::GpioE14", "classmodm_1_1platform_1_1_gpio_e14.html", null ],
          [ "modm::platform::GpioE15", "classmodm_1_1platform_1_1_gpio_e15.html", null ],
          [ "modm::platform::GpioE2", "classmodm_1_1platform_1_1_gpio_e2.html", null ],
          [ "modm::platform::GpioE3", "classmodm_1_1platform_1_1_gpio_e3.html", null ],
          [ "modm::platform::GpioE4", "classmodm_1_1platform_1_1_gpio_e4.html", null ],
          [ "modm::platform::GpioE5", "classmodm_1_1platform_1_1_gpio_e5.html", null ],
          [ "modm::platform::GpioE6", "classmodm_1_1platform_1_1_gpio_e6.html", null ],
          [ "modm::platform::GpioE7", "classmodm_1_1platform_1_1_gpio_e7.html", null ],
          [ "modm::platform::GpioE8", "classmodm_1_1platform_1_1_gpio_e8.html", null ],
          [ "modm::platform::GpioE9", "classmodm_1_1platform_1_1_gpio_e9.html", null ],
          [ "modm::platform::GpioF0", "classmodm_1_1platform_1_1_gpio_f0.html", null ],
          [ "modm::platform::GpioF1", "classmodm_1_1platform_1_1_gpio_f1.html", null ],
          [ "modm::platform::GpioF10", "classmodm_1_1platform_1_1_gpio_f10.html", null ],
          [ "modm::platform::GpioF11", "classmodm_1_1platform_1_1_gpio_f11.html", null ],
          [ "modm::platform::GpioF12", "classmodm_1_1platform_1_1_gpio_f12.html", null ],
          [ "modm::platform::GpioF13", "classmodm_1_1platform_1_1_gpio_f13.html", null ],
          [ "modm::platform::GpioF14", "classmodm_1_1platform_1_1_gpio_f14.html", null ],
          [ "modm::platform::GpioF15", "classmodm_1_1platform_1_1_gpio_f15.html", null ],
          [ "modm::platform::GpioF2", "classmodm_1_1platform_1_1_gpio_f2.html", null ],
          [ "modm::platform::GpioF3", "classmodm_1_1platform_1_1_gpio_f3.html", null ],
          [ "modm::platform::GpioF4", "classmodm_1_1platform_1_1_gpio_f4.html", null ],
          [ "modm::platform::GpioF5", "classmodm_1_1platform_1_1_gpio_f5.html", null ],
          [ "modm::platform::GpioF6", "classmodm_1_1platform_1_1_gpio_f6.html", null ],
          [ "modm::platform::GpioF7", "classmodm_1_1platform_1_1_gpio_f7.html", null ],
          [ "modm::platform::GpioF8", "classmodm_1_1platform_1_1_gpio_f8.html", null ],
          [ "modm::platform::GpioF9", "classmodm_1_1platform_1_1_gpio_f9.html", null ],
          [ "modm::platform::GpioG0", "classmodm_1_1platform_1_1_gpio_g0.html", null ],
          [ "modm::platform::GpioG1", "classmodm_1_1platform_1_1_gpio_g1.html", null ],
          [ "modm::platform::GpioG10", "classmodm_1_1platform_1_1_gpio_g10.html", null ],
          [ "modm::platform::GpioG11", "classmodm_1_1platform_1_1_gpio_g11.html", null ],
          [ "modm::platform::GpioG12", "classmodm_1_1platform_1_1_gpio_g12.html", null ],
          [ "modm::platform::GpioG13", "classmodm_1_1platform_1_1_gpio_g13.html", null ],
          [ "modm::platform::GpioG14", "classmodm_1_1platform_1_1_gpio_g14.html", null ],
          [ "modm::platform::GpioG15", "classmodm_1_1platform_1_1_gpio_g15.html", null ],
          [ "modm::platform::GpioG2", "classmodm_1_1platform_1_1_gpio_g2.html", null ],
          [ "modm::platform::GpioG3", "classmodm_1_1platform_1_1_gpio_g3.html", null ],
          [ "modm::platform::GpioG4", "classmodm_1_1platform_1_1_gpio_g4.html", null ],
          [ "modm::platform::GpioG5", "classmodm_1_1platform_1_1_gpio_g5.html", null ],
          [ "modm::platform::GpioG6", "classmodm_1_1platform_1_1_gpio_g6.html", null ],
          [ "modm::platform::GpioG7", "classmodm_1_1platform_1_1_gpio_g7.html", null ],
          [ "modm::platform::GpioG8", "classmodm_1_1platform_1_1_gpio_g8.html", null ],
          [ "modm::platform::GpioG9", "classmodm_1_1platform_1_1_gpio_g9.html", null ],
          [ "modm::platform::GpioH0", "classmodm_1_1platform_1_1_gpio_h0.html", null ],
          [ "modm::platform::GpioH1", "classmodm_1_1platform_1_1_gpio_h1.html", null ],
          [ "modm::platform::GpioH10", "classmodm_1_1platform_1_1_gpio_h10.html", null ],
          [ "modm::platform::GpioH11", "classmodm_1_1platform_1_1_gpio_h11.html", null ],
          [ "modm::platform::GpioH12", "classmodm_1_1platform_1_1_gpio_h12.html", null ],
          [ "modm::platform::GpioH13", "classmodm_1_1platform_1_1_gpio_h13.html", null ],
          [ "modm::platform::GpioH14", "classmodm_1_1platform_1_1_gpio_h14.html", null ],
          [ "modm::platform::GpioH15", "classmodm_1_1platform_1_1_gpio_h15.html", null ],
          [ "modm::platform::GpioH2", "classmodm_1_1platform_1_1_gpio_h2.html", null ],
          [ "modm::platform::GpioH3", "classmodm_1_1platform_1_1_gpio_h3.html", null ],
          [ "modm::platform::GpioH4", "classmodm_1_1platform_1_1_gpio_h4.html", null ],
          [ "modm::platform::GpioH5", "classmodm_1_1platform_1_1_gpio_h5.html", null ],
          [ "modm::platform::GpioH6", "classmodm_1_1platform_1_1_gpio_h6.html", null ],
          [ "modm::platform::GpioH7", "classmodm_1_1platform_1_1_gpio_h7.html", null ],
          [ "modm::platform::GpioH8", "classmodm_1_1platform_1_1_gpio_h8.html", null ],
          [ "modm::platform::GpioH9", "classmodm_1_1platform_1_1_gpio_h9.html", null ],
          [ "modm::platform::GpioI0", "classmodm_1_1platform_1_1_gpio_i0.html", null ],
          [ "modm::platform::GpioI1", "classmodm_1_1platform_1_1_gpio_i1.html", null ],
          [ "modm::platform::GpioI10", "classmodm_1_1platform_1_1_gpio_i10.html", null ],
          [ "modm::platform::GpioI11", "classmodm_1_1platform_1_1_gpio_i11.html", null ],
          [ "modm::platform::GpioI2", "classmodm_1_1platform_1_1_gpio_i2.html", null ],
          [ "modm::platform::GpioI3", "classmodm_1_1platform_1_1_gpio_i3.html", null ],
          [ "modm::platform::GpioI4", "classmodm_1_1platform_1_1_gpio_i4.html", null ],
          [ "modm::platform::GpioI5", "classmodm_1_1platform_1_1_gpio_i5.html", null ],
          [ "modm::platform::GpioI6", "classmodm_1_1platform_1_1_gpio_i6.html", null ],
          [ "modm::platform::GpioI7", "classmodm_1_1platform_1_1_gpio_i7.html", null ],
          [ "modm::platform::GpioI8", "classmodm_1_1platform_1_1_gpio_i8.html", null ],
          [ "modm::platform::GpioI9", "classmodm_1_1platform_1_1_gpio_i9.html", null ],
          [ "modm::platform::GpioUnused", "classmodm_1_1platform_1_1_gpio_unused.html", null ]
        ] ]
      ] ],
      [ "modm::GpioOutput", "classmodm_1_1_gpio_output.html", [
        [ "modm::GpioIO", "classmodm_1_1_gpio_i_o.html", null ]
      ] ]
    ] ],
    [ "modm::platform::Gpio", "structmodm_1_1platform_1_1_gpio.html", [
      [ "modm::platform::GpioSet< GpioA0 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioA1 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioA10 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioA11 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioA12 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioA13 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioA14 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioA15 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioA2 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioA3 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioA4 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioA5 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioA6 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioA7 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioA8 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioA9 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioB0 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioB1 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioB10 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioB11 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioB12 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioB13 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioB14 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioB15 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioB2 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioB3 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioB4 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioB5 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioB6 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioB7 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioB8 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioB9 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioC0 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioC1 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioC10 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioC11 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioC12 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioC13 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioC14 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioC15 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioC2 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioC3 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioC4 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioC5 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioC6 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioC7 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioC8 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioC9 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioD0 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioD1 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioD10 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioD11 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioD12 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioD13 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioD14 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioD15 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioD2 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioD3 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioD4 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioD5 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioD6 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioD7 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioD8 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioD9 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioE0 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioE1 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioE10 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioE11 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioE12 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioE13 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioE14 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioE15 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioE2 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioE3 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioE4 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioE5 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioE6 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioE7 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioE8 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioE9 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioF0 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioF1 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioF10 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioF11 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioF12 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioF13 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioF14 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioF15 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioF2 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioF3 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioF4 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioF5 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioF6 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioF7 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioF8 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioF9 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioG0 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioG1 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioG10 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioG11 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioG12 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioG13 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioG14 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioG15 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioG2 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioG3 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioG4 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioG5 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioG6 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioG7 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioG8 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioG9 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioH0 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioH1 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioH10 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioH11 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioH12 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioH13 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioH14 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioH15 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioH2 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioH3 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioH4 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioH5 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioH6 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioH7 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioH8 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioH9 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioI0 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioI1 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioI10 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioI11 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioI2 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioI3 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioI4 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioI5 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioI6 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioI7 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioI8 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< GpioI9 >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioSet< Gpios... >", "classmodm_1_1platform_1_1_gpio_set.html", [
        [ "modm::platform::SoftwareGpioPort< Gpios >", "classmodm_1_1platform_1_1_software_gpio_port.html", null ]
      ] ],
      [ "modm::platform::GpioA0", "classmodm_1_1platform_1_1_gpio_a0.html", null ],
      [ "modm::platform::GpioA1", "classmodm_1_1platform_1_1_gpio_a1.html", null ],
      [ "modm::platform::GpioA10", "classmodm_1_1platform_1_1_gpio_a10.html", null ],
      [ "modm::platform::GpioA11", "classmodm_1_1platform_1_1_gpio_a11.html", null ],
      [ "modm::platform::GpioA12", "classmodm_1_1platform_1_1_gpio_a12.html", null ],
      [ "modm::platform::GpioA13", "classmodm_1_1platform_1_1_gpio_a13.html", null ],
      [ "modm::platform::GpioA14", "classmodm_1_1platform_1_1_gpio_a14.html", null ],
      [ "modm::platform::GpioA15", "classmodm_1_1platform_1_1_gpio_a15.html", null ],
      [ "modm::platform::GpioA2", "classmodm_1_1platform_1_1_gpio_a2.html", null ],
      [ "modm::platform::GpioA3", "classmodm_1_1platform_1_1_gpio_a3.html", null ],
      [ "modm::platform::GpioA4", "classmodm_1_1platform_1_1_gpio_a4.html", null ],
      [ "modm::platform::GpioA5", "classmodm_1_1platform_1_1_gpio_a5.html", null ],
      [ "modm::platform::GpioA6", "classmodm_1_1platform_1_1_gpio_a6.html", null ],
      [ "modm::platform::GpioA7", "classmodm_1_1platform_1_1_gpio_a7.html", null ],
      [ "modm::platform::GpioA8", "classmodm_1_1platform_1_1_gpio_a8.html", null ],
      [ "modm::platform::GpioA9", "classmodm_1_1platform_1_1_gpio_a9.html", null ],
      [ "modm::platform::GpioB0", "classmodm_1_1platform_1_1_gpio_b0.html", null ],
      [ "modm::platform::GpioB1", "classmodm_1_1platform_1_1_gpio_b1.html", null ],
      [ "modm::platform::GpioB10", "classmodm_1_1platform_1_1_gpio_b10.html", null ],
      [ "modm::platform::GpioB11", "classmodm_1_1platform_1_1_gpio_b11.html", null ],
      [ "modm::platform::GpioB12", "classmodm_1_1platform_1_1_gpio_b12.html", null ],
      [ "modm::platform::GpioB13", "classmodm_1_1platform_1_1_gpio_b13.html", null ],
      [ "modm::platform::GpioB14", "classmodm_1_1platform_1_1_gpio_b14.html", null ],
      [ "modm::platform::GpioB15", "classmodm_1_1platform_1_1_gpio_b15.html", null ],
      [ "modm::platform::GpioB2", "classmodm_1_1platform_1_1_gpio_b2.html", null ],
      [ "modm::platform::GpioB3", "classmodm_1_1platform_1_1_gpio_b3.html", null ],
      [ "modm::platform::GpioB4", "classmodm_1_1platform_1_1_gpio_b4.html", null ],
      [ "modm::platform::GpioB5", "classmodm_1_1platform_1_1_gpio_b5.html", null ],
      [ "modm::platform::GpioB6", "classmodm_1_1platform_1_1_gpio_b6.html", null ],
      [ "modm::platform::GpioB7", "classmodm_1_1platform_1_1_gpio_b7.html", null ],
      [ "modm::platform::GpioB8", "classmodm_1_1platform_1_1_gpio_b8.html", null ],
      [ "modm::platform::GpioB9", "classmodm_1_1platform_1_1_gpio_b9.html", null ],
      [ "modm::platform::GpioC0", "classmodm_1_1platform_1_1_gpio_c0.html", null ],
      [ "modm::platform::GpioC1", "classmodm_1_1platform_1_1_gpio_c1.html", null ],
      [ "modm::platform::GpioC10", "classmodm_1_1platform_1_1_gpio_c10.html", null ],
      [ "modm::platform::GpioC11", "classmodm_1_1platform_1_1_gpio_c11.html", null ],
      [ "modm::platform::GpioC12", "classmodm_1_1platform_1_1_gpio_c12.html", null ],
      [ "modm::platform::GpioC13", "classmodm_1_1platform_1_1_gpio_c13.html", null ],
      [ "modm::platform::GpioC14", "classmodm_1_1platform_1_1_gpio_c14.html", null ],
      [ "modm::platform::GpioC15", "classmodm_1_1platform_1_1_gpio_c15.html", null ],
      [ "modm::platform::GpioC2", "classmodm_1_1platform_1_1_gpio_c2.html", null ],
      [ "modm::platform::GpioC3", "classmodm_1_1platform_1_1_gpio_c3.html", null ],
      [ "modm::platform::GpioC4", "classmodm_1_1platform_1_1_gpio_c4.html", null ],
      [ "modm::platform::GpioC5", "classmodm_1_1platform_1_1_gpio_c5.html", null ],
      [ "modm::platform::GpioC6", "classmodm_1_1platform_1_1_gpio_c6.html", null ],
      [ "modm::platform::GpioC7", "classmodm_1_1platform_1_1_gpio_c7.html", null ],
      [ "modm::platform::GpioC8", "classmodm_1_1platform_1_1_gpio_c8.html", null ],
      [ "modm::platform::GpioC9", "classmodm_1_1platform_1_1_gpio_c9.html", null ],
      [ "modm::platform::GpioD0", "classmodm_1_1platform_1_1_gpio_d0.html", null ],
      [ "modm::platform::GpioD1", "classmodm_1_1platform_1_1_gpio_d1.html", null ],
      [ "modm::platform::GpioD10", "classmodm_1_1platform_1_1_gpio_d10.html", null ],
      [ "modm::platform::GpioD11", "classmodm_1_1platform_1_1_gpio_d11.html", null ],
      [ "modm::platform::GpioD12", "classmodm_1_1platform_1_1_gpio_d12.html", null ],
      [ "modm::platform::GpioD13", "classmodm_1_1platform_1_1_gpio_d13.html", null ],
      [ "modm::platform::GpioD14", "classmodm_1_1platform_1_1_gpio_d14.html", null ],
      [ "modm::platform::GpioD15", "classmodm_1_1platform_1_1_gpio_d15.html", null ],
      [ "modm::platform::GpioD2", "classmodm_1_1platform_1_1_gpio_d2.html", null ],
      [ "modm::platform::GpioD3", "classmodm_1_1platform_1_1_gpio_d3.html", null ],
      [ "modm::platform::GpioD4", "classmodm_1_1platform_1_1_gpio_d4.html", null ],
      [ "modm::platform::GpioD5", "classmodm_1_1platform_1_1_gpio_d5.html", null ],
      [ "modm::platform::GpioD6", "classmodm_1_1platform_1_1_gpio_d6.html", null ],
      [ "modm::platform::GpioD7", "classmodm_1_1platform_1_1_gpio_d7.html", null ],
      [ "modm::platform::GpioD8", "classmodm_1_1platform_1_1_gpio_d8.html", null ],
      [ "modm::platform::GpioD9", "classmodm_1_1platform_1_1_gpio_d9.html", null ],
      [ "modm::platform::GpioE0", "classmodm_1_1platform_1_1_gpio_e0.html", null ],
      [ "modm::platform::GpioE1", "classmodm_1_1platform_1_1_gpio_e1.html", null ],
      [ "modm::platform::GpioE10", "classmodm_1_1platform_1_1_gpio_e10.html", null ],
      [ "modm::platform::GpioE11", "classmodm_1_1platform_1_1_gpio_e11.html", null ],
      [ "modm::platform::GpioE12", "classmodm_1_1platform_1_1_gpio_e12.html", null ],
      [ "modm::platform::GpioE13", "classmodm_1_1platform_1_1_gpio_e13.html", null ],
      [ "modm::platform::GpioE14", "classmodm_1_1platform_1_1_gpio_e14.html", null ],
      [ "modm::platform::GpioE15", "classmodm_1_1platform_1_1_gpio_e15.html", null ],
      [ "modm::platform::GpioE2", "classmodm_1_1platform_1_1_gpio_e2.html", null ],
      [ "modm::platform::GpioE3", "classmodm_1_1platform_1_1_gpio_e3.html", null ],
      [ "modm::platform::GpioE4", "classmodm_1_1platform_1_1_gpio_e4.html", null ],
      [ "modm::platform::GpioE5", "classmodm_1_1platform_1_1_gpio_e5.html", null ],
      [ "modm::platform::GpioE6", "classmodm_1_1platform_1_1_gpio_e6.html", null ],
      [ "modm::platform::GpioE7", "classmodm_1_1platform_1_1_gpio_e7.html", null ],
      [ "modm::platform::GpioE8", "classmodm_1_1platform_1_1_gpio_e8.html", null ],
      [ "modm::platform::GpioE9", "classmodm_1_1platform_1_1_gpio_e9.html", null ],
      [ "modm::platform::GpioF0", "classmodm_1_1platform_1_1_gpio_f0.html", null ],
      [ "modm::platform::GpioF1", "classmodm_1_1platform_1_1_gpio_f1.html", null ],
      [ "modm::platform::GpioF10", "classmodm_1_1platform_1_1_gpio_f10.html", null ],
      [ "modm::platform::GpioF11", "classmodm_1_1platform_1_1_gpio_f11.html", null ],
      [ "modm::platform::GpioF12", "classmodm_1_1platform_1_1_gpio_f12.html", null ],
      [ "modm::platform::GpioF13", "classmodm_1_1platform_1_1_gpio_f13.html", null ],
      [ "modm::platform::GpioF14", "classmodm_1_1platform_1_1_gpio_f14.html", null ],
      [ "modm::platform::GpioF15", "classmodm_1_1platform_1_1_gpio_f15.html", null ],
      [ "modm::platform::GpioF2", "classmodm_1_1platform_1_1_gpio_f2.html", null ],
      [ "modm::platform::GpioF3", "classmodm_1_1platform_1_1_gpio_f3.html", null ],
      [ "modm::platform::GpioF4", "classmodm_1_1platform_1_1_gpio_f4.html", null ],
      [ "modm::platform::GpioF5", "classmodm_1_1platform_1_1_gpio_f5.html", null ],
      [ "modm::platform::GpioF6", "classmodm_1_1platform_1_1_gpio_f6.html", null ],
      [ "modm::platform::GpioF7", "classmodm_1_1platform_1_1_gpio_f7.html", null ],
      [ "modm::platform::GpioF8", "classmodm_1_1platform_1_1_gpio_f8.html", null ],
      [ "modm::platform::GpioF9", "classmodm_1_1platform_1_1_gpio_f9.html", null ],
      [ "modm::platform::GpioG0", "classmodm_1_1platform_1_1_gpio_g0.html", null ],
      [ "modm::platform::GpioG1", "classmodm_1_1platform_1_1_gpio_g1.html", null ],
      [ "modm::platform::GpioG10", "classmodm_1_1platform_1_1_gpio_g10.html", null ],
      [ "modm::platform::GpioG11", "classmodm_1_1platform_1_1_gpio_g11.html", null ],
      [ "modm::platform::GpioG12", "classmodm_1_1platform_1_1_gpio_g12.html", null ],
      [ "modm::platform::GpioG13", "classmodm_1_1platform_1_1_gpio_g13.html", null ],
      [ "modm::platform::GpioG14", "classmodm_1_1platform_1_1_gpio_g14.html", null ],
      [ "modm::platform::GpioG15", "classmodm_1_1platform_1_1_gpio_g15.html", null ],
      [ "modm::platform::GpioG2", "classmodm_1_1platform_1_1_gpio_g2.html", null ],
      [ "modm::platform::GpioG3", "classmodm_1_1platform_1_1_gpio_g3.html", null ],
      [ "modm::platform::GpioG4", "classmodm_1_1platform_1_1_gpio_g4.html", null ],
      [ "modm::platform::GpioG5", "classmodm_1_1platform_1_1_gpio_g5.html", null ],
      [ "modm::platform::GpioG6", "classmodm_1_1platform_1_1_gpio_g6.html", null ],
      [ "modm::platform::GpioG7", "classmodm_1_1platform_1_1_gpio_g7.html", null ],
      [ "modm::platform::GpioG8", "classmodm_1_1platform_1_1_gpio_g8.html", null ],
      [ "modm::platform::GpioG9", "classmodm_1_1platform_1_1_gpio_g9.html", null ],
      [ "modm::platform::GpioH0", "classmodm_1_1platform_1_1_gpio_h0.html", null ],
      [ "modm::platform::GpioH1", "classmodm_1_1platform_1_1_gpio_h1.html", null ],
      [ "modm::platform::GpioH10", "classmodm_1_1platform_1_1_gpio_h10.html", null ],
      [ "modm::platform::GpioH11", "classmodm_1_1platform_1_1_gpio_h11.html", null ],
      [ "modm::platform::GpioH12", "classmodm_1_1platform_1_1_gpio_h12.html", null ],
      [ "modm::platform::GpioH13", "classmodm_1_1platform_1_1_gpio_h13.html", null ],
      [ "modm::platform::GpioH14", "classmodm_1_1platform_1_1_gpio_h14.html", null ],
      [ "modm::platform::GpioH15", "classmodm_1_1platform_1_1_gpio_h15.html", null ],
      [ "modm::platform::GpioH2", "classmodm_1_1platform_1_1_gpio_h2.html", null ],
      [ "modm::platform::GpioH3", "classmodm_1_1platform_1_1_gpio_h3.html", null ],
      [ "modm::platform::GpioH4", "classmodm_1_1platform_1_1_gpio_h4.html", null ],
      [ "modm::platform::GpioH5", "classmodm_1_1platform_1_1_gpio_h5.html", null ],
      [ "modm::platform::GpioH6", "classmodm_1_1platform_1_1_gpio_h6.html", null ],
      [ "modm::platform::GpioH7", "classmodm_1_1platform_1_1_gpio_h7.html", null ],
      [ "modm::platform::GpioH8", "classmodm_1_1platform_1_1_gpio_h8.html", null ],
      [ "modm::platform::GpioH9", "classmodm_1_1platform_1_1_gpio_h9.html", null ],
      [ "modm::platform::GpioI0", "classmodm_1_1platform_1_1_gpio_i0.html", null ],
      [ "modm::platform::GpioI1", "classmodm_1_1platform_1_1_gpio_i1.html", null ],
      [ "modm::platform::GpioI10", "classmodm_1_1platform_1_1_gpio_i10.html", null ],
      [ "modm::platform::GpioI11", "classmodm_1_1platform_1_1_gpio_i11.html", null ],
      [ "modm::platform::GpioI2", "classmodm_1_1platform_1_1_gpio_i2.html", null ],
      [ "modm::platform::GpioI3", "classmodm_1_1platform_1_1_gpio_i3.html", null ],
      [ "modm::platform::GpioI4", "classmodm_1_1platform_1_1_gpio_i4.html", null ],
      [ "modm::platform::GpioI5", "classmodm_1_1platform_1_1_gpio_i5.html", null ],
      [ "modm::platform::GpioI6", "classmodm_1_1platform_1_1_gpio_i6.html", null ],
      [ "modm::platform::GpioI7", "classmodm_1_1platform_1_1_gpio_i7.html", null ],
      [ "modm::platform::GpioI8", "classmodm_1_1platform_1_1_gpio_i8.html", null ],
      [ "modm::platform::GpioI9", "classmodm_1_1platform_1_1_gpio_i9.html", null ],
      [ "modm::platform::GpioSet< Gpios >", "classmodm_1_1platform_1_1_gpio_set.html", null ],
      [ "modm::platform::GpioUnused", "classmodm_1_1platform_1_1_gpio_unused.html", null ]
    ] ],
    [ "modm::GpioPort", "classmodm_1_1_gpio_port.html", [
      [ "modm::platform::GpioPort< StartGpio, Width >", "classmodm_1_1platform_1_1_gpio_port.html", null ],
      [ "modm::platform::SoftwareGpioPort< Gpios >", "classmodm_1_1platform_1_1_software_gpio_port.html", null ]
    ] ],
    [ "modm::platform::HeapTable", "classmodm_1_1platform_1_1_heap_table.html", null ],
    [ "modm::I2c", "structmodm_1_1_i2c.html", [
      [ "modm::I2cMaster", "classmodm_1_1_i2c_master.html", [
        [ "modm::platform::I2cMaster3", "classmodm_1_1platform_1_1_i2c_master3.html", null ]
      ] ],
      [ "modm::I2cTransaction", "classmodm_1_1_i2c_transaction.html", [
        [ "modm::I2cReadTransaction", "classmodm_1_1_i2c_read_transaction.html", null ],
        [ "modm::I2cWriteReadTransaction", "classmodm_1_1_i2c_write_read_transaction.html", null ],
        [ "modm::I2cWriteTransaction", "classmodm_1_1_i2c_write_transaction.html", null ]
      ] ]
    ] ],
    [ "modm::inplace_any&lt; Size &gt;", "classmodm_1_1inplace__any.html", null ],
    [ "modm::IODevice", "classmodm_1_1_i_o_device.html", [
      [ "modm::IODeviceObjectWrapper< Device, behavior >", "classmodm_1_1_i_o_device_object_wrapper.html", null ],
      [ "modm::IODeviceWrapper< Device, behavior >", "classmodm_1_1_i_o_device_wrapper.html", null ],
      [ "modm::log::StyleWrapper< STYLE >", "classmodm_1_1log_1_1_style_wrapper.html", null ]
    ] ],
    [ "modm::IOStream", "classmodm_1_1_i_o_stream.html", [
      [ "modm::log::Logger", "classmodm_1_1log_1_1_logger.html", null ]
    ] ],
    [ "std::iterator", null, [
      [ "modm::BoundedDeque< T, N >::const_iterator", "classmodm_1_1_bounded_deque_1_1const__iterator.html", null ],
      [ "modm::DoublyLinkedList< T, Allocator >::const_iterator", "classmodm_1_1_doubly_linked_list_1_1const__iterator.html", null ],
      [ "modm::DoublyLinkedList< T, Allocator >::iterator", "classmodm_1_1_doubly_linked_list_1_1iterator.html", null ],
      [ "modm::DynamicArray< T, Allocator >::const_iterator", "classmodm_1_1_dynamic_array_1_1const__iterator.html", null ],
      [ "modm::DynamicArray< T, Allocator >::iterator", "classmodm_1_1_dynamic_array_1_1iterator.html", null ],
      [ "modm::LinkedList< T, Allocator >::const_iterator", "classmodm_1_1_linked_list_1_1const__iterator.html", null ],
      [ "modm::LinkedList< T, Allocator >::iterator", "classmodm_1_1_linked_list_1_1iterator.html", null ]
    ] ],
    [ "modm::interpolation::Lagrange&lt; T, Accessor &gt;", "classmodm_1_1interpolation_1_1_lagrange.html", null ],
    [ "modm::Line2D&lt; T &gt;", "classmodm_1_1_line2_d.html", null ],
    [ "modm::interpolation::Linear&lt; T, Accessor &gt;", "classmodm_1_1interpolation_1_1_linear.html", null ],
    [ "modm::LineSegment2D&lt; T &gt;", "classmodm_1_1_line_segment2_d.html", null ],
    [ "modm::LinkedList&lt; T, Allocator &gt;", "classmodm_1_1_linked_list.html", null ],
    [ "modm::Location2D&lt; T &gt;", "classmodm_1_1_location2_d.html", null ],
    [ "modm::LUDecomposition", "classmodm_1_1_l_u_decomposition.html", null ],
    [ "modm::detail::MakeSigned&lt; Vector&lt; T, N &gt; &gt;", "structmodm_1_1detail_1_1_make_signed_3_01_vector_3_01_t_00_01_n_01_4_01_4.html", null ],
    [ "modm::detail::MakeUnsigned&lt; Vector&lt; T, N &gt; &gt;", "structmodm_1_1detail_1_1_make_unsigned_3_01_vector_3_01_t_00_01_n_01_4_01_4.html", null ],
    [ "modm::Matrix&lt; T, ROWS, COLUMNS &gt;", "classmodm_1_1_matrix.html", null ],
    [ "modm::filter::Median&lt; T, N &gt;", "classmodm_1_1filter_1_1_median.html", null ],
    [ "modm::filter::Median&lt; T, 3 &gt;", "classmodm_1_1filter_1_1_median_3_01_t_00_013_01_4.html", null ],
    [ "modm::filter::Median&lt; T, 5 &gt;", "classmodm_1_1filter_1_1_median_3_01_t_00_015_01_4.html", null ],
    [ "modm::filter::Median&lt; T, 7 &gt;", "classmodm_1_1filter_1_1_median_3_01_t_00_017_01_4.html", null ],
    [ "modm::filter::Median&lt; T, 9 &gt;", "classmodm_1_1filter_1_1_median_3_01_t_00_019_01_4.html", null ],
    [ "mem_pool_t", "structmem__pool__t.html", null ],
    [ "modm::can::Message", "structmodm_1_1can_1_1_message.html", null ],
    [ "modm::chrono::micro_clock", "structmodm_1_1chrono_1_1micro__clock.html", null ],
    [ "modm::chrono::milli_clock", "structmodm_1_1chrono_1_1milli__clock.html", null ],
    [ "modm::filter::MovingAverage&lt; T, N &gt;", "classmodm_1_1filter_1_1_moving_average.html", null ],
    [ "modm::filter::MovingAverage&lt; double, N &gt;", "classmodm_1_1filter_1_1_moving_average_3_01double_00_01_n_01_4.html", null ],
    [ "modm::NestedResumable&lt; Levels &gt;", "classmodm_1_1_nested_resumable.html", null ],
    [ "modm::NestedResumable&lt; 10+1 &gt;", "classmodm_1_1_nested_resumable.html", [
      [ "modm::I2cDevice< I2cMaster, NestingLevels, Transaction >", "classmodm_1_1_i2c_device.html", null ]
    ] ],
    [ "modm::NestedResumable&lt; NestingLevels+1 &gt;", "classmodm_1_1_nested_resumable.html", [
      [ "modm::I2cDevice< I2cMaster, 4 >", "classmodm_1_1_i2c_device.html", [
        [ "modm::Bno055< I2cMaster >", "classmodm_1_1_bno055.html", null ]
      ] ]
    ] ],
    [ "modm::DoublyLinkedList&lt; T, Allocator &gt;::Node", "structmodm_1_1_doubly_linked_list_1_1_node.html", null ],
    [ "modm::LinkedList&lt; T, Allocator &gt;::Node", "structmodm_1_1_linked_list_1_1_node.html", null ],
    [ "modm::Pair&lt; T1, T2 &gt;", "classmodm_1_1_pair.html", null ],
    [ "modm::Pid&lt; T, ScaleFactor &gt;::Parameter", "structmodm_1_1_pid_1_1_parameter.html", null ],
    [ "modm::SCurveController&lt; T &gt;::Parameter", "structmodm_1_1_s_curve_controller_1_1_parameter.html", null ],
    [ "modm::PeripheralDriver", "classmodm_1_1_peripheral_driver.html", [
      [ "modm::Adc", "classmodm_1_1_adc.html", [
        [ "modm::AdcInterrupt", "classmodm_1_1_adc_interrupt.html", [
          [ "modm::platform::AdcInterrupt1", "classmodm_1_1platform_1_1_adc_interrupt1.html", null ],
          [ "modm::platform::AdcInterrupt3", "classmodm_1_1platform_1_1_adc_interrupt3.html", null ]
        ] ],
        [ "modm::platform::Adc1", "classmodm_1_1platform_1_1_adc1.html", [
          [ "modm::platform::AdcInterrupt1", "classmodm_1_1platform_1_1_adc_interrupt1.html", null ]
        ] ],
        [ "modm::platform::Adc3", "classmodm_1_1platform_1_1_adc3.html", [
          [ "modm::platform::AdcInterrupt3", "classmodm_1_1platform_1_1_adc_interrupt3.html", null ]
        ] ]
      ] ],
      [ "modm::Can", "classmodm_1_1_can.html", [
        [ "modm::platform::Can1", "classmodm_1_1platform_1_1_can1.html", null ],
        [ "modm::platform::Can2", "classmodm_1_1platform_1_1_can2.html", null ]
      ] ],
      [ "modm::I2cMaster", "classmodm_1_1_i2c_master.html", null ],
      [ "modm::SpiMaster", "classmodm_1_1_spi_master.html", [
        [ "modm::platform::SpiMaster1", "classmodm_1_1platform_1_1_spi_master1.html", null ],
        [ "modm::platform::SpiMaster2", "classmodm_1_1platform_1_1_spi_master2.html", null ]
      ] ],
      [ "modm::Uart", "classmodm_1_1_uart.html", [
        [ "modm::platform::Usart1", "classmodm_1_1platform_1_1_usart1.html", null ],
        [ "modm::platform::Usart3", "classmodm_1_1platform_1_1_usart3.html", null ],
        [ "modm::platform::Usart6", "classmodm_1_1platform_1_1_usart6.html", null ]
      ] ]
    ] ],
    [ "modm::Pid&lt; T, ScaleFactor &gt;", "classmodm_1_1_pid.html", null ],
    [ "Pin", null, [
      [ "modm::platform::GpioInverted< typename Pin::Output >", "classmodm_1_1platform_1_1_gpio_inverted.html", null ],
      [ "modm::platform::GpioInverted< typename Pin::Input >", "classmodm_1_1platform_1_1_gpio_inverted.html", null ],
      [ "modm::platform::GpioInverted< typename Pin::IO >", "classmodm_1_1platform_1_1_gpio_inverted.html", null ],
      [ "modm::platform::GpioInverted< Pin >", "classmodm_1_1platform_1_1_gpio_inverted.html", null ]
    ] ],
    [ "modm::platform::Rcc::PllFactors", "structmodm_1_1platform_1_1_rcc_1_1_pll_factors.html", null ],
    [ "modm::PointSet2D&lt; T &gt;", "classmodm_1_1_point_set2_d.html", [
      [ "modm::Polygon2D< T >", "classmodm_1_1_polygon2_d.html", null ]
    ] ],
    [ "modm::pt::Protothread", "classmodm_1_1pt_1_1_protothread.html", null ],
    [ "modm::Quaternion&lt; T &gt;", "classmodm_1_1_quaternion.html", null ],
    [ "modm::atomic::Queue&lt; T, N &gt;", "classmodm_1_1atomic_1_1_queue.html", null ],
    [ "modm::Queue&lt; T, Container &gt;", "classmodm_1_1_queue.html", [
      [ "modm::BoundedQueue< T, N, Container >", "classmodm_1_1_bounded_queue.html", null ]
    ] ],
    [ "modm::accessor::Ram&lt; T &gt;", "classmodm_1_1accessor_1_1_ram.html", null ],
    [ "modm::filter::Ramp&lt; T &gt;", "classmodm_1_1filter_1_1_ramp.html", null ],
    [ "modm::platform::RandomNumberGenerator", "classmodm_1_1platform_1_1_random_number_generator.html", null ],
    [ "modm::Ray2D&lt; T &gt;", "classmodm_1_1_ray2_d.html", null ],
    [ "modm::platform::Rcc", "classmodm_1_1platform_1_1_rcc.html", null ],
    [ "modm::I2cTransaction::Reading", "structmodm_1_1_i2c_transaction_1_1_reading.html", null ],
    [ "modm::allocator::Block&lt; T, BLOCKSIZE &gt;::rebind&lt; U &gt;", "structmodm_1_1allocator_1_1_block_1_1rebind.html", null ],
    [ "modm::allocator::Dynamic&lt; T &gt;::rebind&lt; U &gt;", "structmodm_1_1allocator_1_1_dynamic_1_1rebind.html", null ],
    [ "modm::allocator::Static&lt; T, N &gt;::rebind&lt; U &gt;", "structmodm_1_1allocator_1_1_static_1_1rebind.html", null ],
    [ "modm::Register&lt; T &gt;", "structmodm_1_1_register.html", [
      [ "modm::FlagsOperators< Enum, T >", "structmodm_1_1_flags_operators.html", [
        [ "modm::Flags< Enum, uint8_t >", "structmodm_1_1_flags.html", null ],
        [ "modm::Flags< Enum, uint16_t >", "structmodm_1_1_flags.html", null ],
        [ "modm::Flags< Enum, uint32_t >", "structmodm_1_1_flags.html", null ],
        [ "modm::Flags< Enum, T >", "structmodm_1_1_flags.html", null ]
      ] ]
    ] ],
    [ "modm::Register&lt; Parent::UnderlyingType &gt;", "structmodm_1_1_register.html", [
      [ "modm::FlagsOperators< Parent::EnumType, Parent::UnderlyingType >", "structmodm_1_1_flags_operators.html", [
        [ "modm::Configuration< Parent, Enum, Mask, Position >", "structmodm_1_1_configuration.html", null ],
        [ "modm::Value< Parent, Width, Position >", "structmodm_1_1_value.html", null ]
      ] ]
    ] ],
    [ "modm::Register&lt; T::UnderlyingType &gt;", "structmodm_1_1_register.html", [
      [ "modm::FlagsGroup< T >", "structmodm_1_1_flags_group_3_01_t_01_4.html", null ]
    ] ],
    [ "modm::GenericPrescaler&lt; T &gt;::Result", "structmodm_1_1_generic_prescaler_1_1_result.html", null ],
    [ "modm::Resumable&lt; Functions &gt;", "classmodm_1_1_resumable.html", null ],
    [ "modm::ResumableResult&lt; T &gt;", "structmodm_1_1_resumable_result.html", null ],
    [ "RxMessage", "struct_rx_message.html", null ],
    [ "modm::Saturated&lt; T &gt;", "classmodm_1_1_saturated.html", null ],
    [ "modm::SCurveController&lt; T &gt;", "classmodm_1_1_s_curve_controller.html", null ],
    [ "modm::SCurveGenerator&lt; T &gt;", "classmodm_1_1_s_curve_generator.html", null ],
    [ "modm::pt::Semaphore", "classmodm_1_1pt_1_1_semaphore.html", null ],
    [ "modm::SmartPointer", "classmodm_1_1_smart_pointer.html", null ],
    [ "modm::Spi", "structmodm_1_1_spi.html", [
      [ "modm::SpiMaster", "classmodm_1_1_spi_master.html", null ]
    ] ],
    [ "modm::platform::SpiBase", "classmodm_1_1platform_1_1_spi_base.html", [
      [ "modm::platform::SpiHal1", "classmodm_1_1platform_1_1_spi_hal1.html", null ],
      [ "modm::platform::SpiHal2", "classmodm_1_1platform_1_1_spi_hal2.html", null ]
    ] ],
    [ "modm::SpiDevice&lt; SpiMaster &gt;", "classmodm_1_1_spi_device.html", null ],
    [ "modm::Stack&lt; T, Container &gt;", "classmodm_1_1_stack.html", [
      [ "modm::BoundedStack< T, N, Container >", "classmodm_1_1_bounded_stack.html", null ]
    ] ],
    [ "modm::platform::CanFilter::StandardFilterMask", "structmodm_1_1platform_1_1_can_filter_1_1_standard_filter_mask.html", null ],
    [ "modm::platform::CanFilter::StandardFilterMaskShort", "structmodm_1_1platform_1_1_can_filter_1_1_standard_filter_mask_short.html", null ],
    [ "modm::can::StandardIdentifier", "structmodm_1_1can_1_1_standard_identifier.html", null ],
    [ "modm::platform::CanFilter::StandardIdentifier", "structmodm_1_1platform_1_1_can_filter_1_1_standard_identifier.html", null ],
    [ "modm::platform::CanFilter::StandardIdentifierShort", "structmodm_1_1platform_1_1_can_filter_1_1_standard_identifier_short.html", null ],
    [ "modm::can::StandardMask", "structmodm_1_1can_1_1_standard_mask.html", null ],
    [ "modm::I2cTransaction::Starting", "structmodm_1_1_i2c_transaction_1_1_starting.html", null ],
    [ "modm::log::Style&lt; STYLE &gt;", "classmodm_1_1log_1_1_style.html", null ],
    [ "modm::log::Style&lt; DefaultStyle &gt;", "classmodm_1_1log_1_1_style.html", [
      [ "modm::log::Prefix< T, STYLE >", "classmodm_1_1log_1_1_prefix.html", null ],
      [ "modm::log::StdColour< TEXT, BACKGROUND, STYLE >", "classmodm_1_1log_1_1_std_colour.html", null ]
    ] ],
    [ "modm::cortex::SysTickTimer", "classmodm_1_1cortex_1_1_sys_tick_timer.html", null ],
    [ "modm::platform::SysTickTimer", "classmodm_1_1platform_1_1_sys_tick_timer.html", null ],
    [ "table_pool_t", "structtable__pool__t.html", null ],
    [ "modm::Task", "classmodm_1_1_task.html", null ],
    [ "modm::Tolerance", "classmodm_1_1_tolerance.html", null ],
    [ "modm::platform::UartBase", "classmodm_1_1platform_1_1_uart_base.html", [
      [ "modm::platform::Usart1", "classmodm_1_1platform_1_1_usart1.html", null ],
      [ "modm::platform::Usart3", "classmodm_1_1platform_1_1_usart3.html", null ],
      [ "modm::platform::Usart6", "classmodm_1_1platform_1_1_usart6.html", null ],
      [ "modm::platform::UsartHal1", "classmodm_1_1platform_1_1_usart_hal1.html", null ],
      [ "modm::platform::UsartHal3", "classmodm_1_1platform_1_1_usart_hal3.html", null ],
      [ "modm::platform::UsartHal6", "classmodm_1_1platform_1_1_usart_hal6.html", null ]
    ] ],
    [ "modm::Vector&lt; T, N &gt;", "classmodm_1_1_vector.html", null ],
    [ "modm::Vector&lt; T, 1 &gt;", "classmodm_1_1_vector_3_01_t_00_011_01_4.html", null ],
    [ "modm::Vector&lt; T, 2 &gt;", "classmodm_1_1_vector_3_01_t_00_012_01_4.html", null ],
    [ "modm::Vector&lt; T, 3 &gt;", "classmodm_1_1_vector_3_01_t_00_013_01_4.html", null ],
    [ "modm::Vector&lt; T, 4 &gt;", "classmodm_1_1_vector_3_01_t_00_014_01_4.html", null ],
    [ "modm::detail::WideType&lt; Vector&lt; T, N &gt; &gt;", "structmodm_1_1detail_1_1_wide_type_3_01_vector_3_01_t_00_01_n_01_4_01_4.html", null ],
    [ "modm::I2cTransaction::Writing", "structmodm_1_1_i2c_transaction_1_1_writing.html", null ]
];