var namespaces_dup =
[
    [ "modm", null, [
      [ "log", "namespacemodm_1_1log.html", "namespacemodm_1_1log" ],
      [ "filter", "namespacemodm_1_1filter.html", "namespacemodm_1_1filter" ],
      [ "Adc", "classmodm_1_1_adc.html", null ],
      [ "AdcInterrupt", "classmodm_1_1_adc_interrupt.html", null ],
      [ "AssertionInfo", "structmodm_1_1_assertion_info.html", "structmodm_1_1_assertion_info" ],
      [ "Can", "classmodm_1_1_can.html", "classmodm_1_1_can" ],
      [ "Gpio", "structmodm_1_1_gpio.html", "structmodm_1_1_gpio" ],
      [ "GpioInput", "classmodm_1_1_gpio_input.html", null ],
      [ "GpioOutput", "classmodm_1_1_gpio_output.html", null ],
      [ "GpioIO", "classmodm_1_1_gpio_i_o.html", null ],
      [ "GpioPort", "classmodm_1_1_gpio_port.html", "classmodm_1_1_gpio_port" ],
      [ "I2c", "structmodm_1_1_i2c.html", "structmodm_1_1_i2c" ],
      [ "I2cDevice", "classmodm_1_1_i2c_device.html", "classmodm_1_1_i2c_device" ],
      [ "I2cMaster", "classmodm_1_1_i2c_master.html", "classmodm_1_1_i2c_master" ],
      [ "I2cTransaction", "classmodm_1_1_i2c_transaction.html", "classmodm_1_1_i2c_transaction" ],
      [ "I2cWriteReadTransaction", "classmodm_1_1_i2c_write_read_transaction.html", "classmodm_1_1_i2c_write_read_transaction" ],
      [ "I2cWriteTransaction", "classmodm_1_1_i2c_write_transaction.html", "classmodm_1_1_i2c_write_transaction" ],
      [ "I2cReadTransaction", "classmodm_1_1_i2c_read_transaction.html", "classmodm_1_1_i2c_read_transaction" ],
      [ "PeripheralDriver", "classmodm_1_1_peripheral_driver.html", null ],
      [ "Register", "structmodm_1_1_register.html", "structmodm_1_1_register" ],
      [ "FlagsOperators", "structmodm_1_1_flags_operators.html", "structmodm_1_1_flags_operators" ],
      [ "Flags", "structmodm_1_1_flags.html", "structmodm_1_1_flags" ],
      [ "FlagsGroup&lt; T &gt;", "structmodm_1_1_flags_group_3_01_t_01_4.html", "structmodm_1_1_flags_group_3_01_t_01_4" ],
      [ "Configuration", "structmodm_1_1_configuration.html", "structmodm_1_1_configuration" ],
      [ "Value", "structmodm_1_1_value.html", "structmodm_1_1_value" ],
      [ "Spi", "structmodm_1_1_spi.html", "structmodm_1_1_spi" ],
      [ "SpiDevice", "classmodm_1_1_spi_device.html", null ],
      [ "SpiMaster", "classmodm_1_1_spi_master.html", null ],
      [ "Uart", "classmodm_1_1_uart.html", null ],
      [ "BoundedDeque", "classmodm_1_1_bounded_deque.html", "classmodm_1_1_bounded_deque" ],
      [ "DoublyLinkedList", "classmodm_1_1_doubly_linked_list.html", "classmodm_1_1_doubly_linked_list" ],
      [ "DynamicArray", "classmodm_1_1_dynamic_array.html", "classmodm_1_1_dynamic_array" ],
      [ "LinkedList", "classmodm_1_1_linked_list.html", "classmodm_1_1_linked_list" ],
      [ "Pair", "classmodm_1_1_pair.html", null ],
      [ "Queue", "classmodm_1_1_queue.html", "classmodm_1_1_queue" ],
      [ "BoundedQueue", "classmodm_1_1_bounded_queue.html", null ],
      [ "SmartPointer", "classmodm_1_1_smart_pointer.html", "classmodm_1_1_smart_pointer" ],
      [ "Stack", "classmodm_1_1_stack.html", null ],
      [ "BoundedStack", "classmodm_1_1_bounded_stack.html", null ],
      [ "Bno055", "classmodm_1_1_bno055.html", "classmodm_1_1_bno055" ],
      [ "bno055", "structmodm_1_1bno055.html", "structmodm_1_1bno055" ],
      [ "IODevice", "classmodm_1_1_i_o_device.html", "classmodm_1_1_i_o_device" ],
      [ "IODeviceWrapper", "classmodm_1_1_i_o_device_wrapper.html", "classmodm_1_1_i_o_device_wrapper" ],
      [ "IODeviceObjectWrapper", "classmodm_1_1_i_o_device_object_wrapper.html", "classmodm_1_1_i_o_device_object_wrapper" ],
      [ "IOStream", "classmodm_1_1_i_o_stream.html", "classmodm_1_1_i_o_stream" ],
      [ "GenericPrescaler", "classmodm_1_1_generic_prescaler.html", "classmodm_1_1_generic_prescaler" ],
      [ "Pid", "classmodm_1_1_pid.html", "classmodm_1_1_pid" ],
      [ "SCurveController", "classmodm_1_1_s_curve_controller.html", "classmodm_1_1_s_curve_controller" ],
      [ "SCurveGenerator", "classmodm_1_1_s_curve_generator.html", null ],
      [ "Angle", "classmodm_1_1_angle.html", null ],
      [ "Line2D", "classmodm_1_1_line2_d.html", "classmodm_1_1_line2_d" ],
      [ "LineSegment2D", "classmodm_1_1_line_segment2_d.html", "classmodm_1_1_line_segment2_d" ],
      [ "Polygon2D", "classmodm_1_1_polygon2_d.html", "classmodm_1_1_polygon2_d" ],
      [ "Circle2D", "classmodm_1_1_circle2_d.html", "classmodm_1_1_circle2_d" ],
      [ "GeometricTraits", "structmodm_1_1_geometric_traits.html", null ],
      [ "GeometricTraits&lt; int8_t &gt;", "structmodm_1_1_geometric_traits_3_01int8__t_01_4.html", null ],
      [ "GeometricTraits&lt; uint8_t &gt;", "structmodm_1_1_geometric_traits_3_01uint8__t_01_4.html", null ],
      [ "GeometricTraits&lt; int16_t &gt;", "structmodm_1_1_geometric_traits_3_01int16__t_01_4.html", null ],
      [ "GeometricTraits&lt; int32_t &gt;", "structmodm_1_1_geometric_traits_3_01int32__t_01_4.html", null ],
      [ "GeometricTraits&lt; float &gt;", "structmodm_1_1_geometric_traits_3_01float_01_4.html", null ],
      [ "GeometricTraits&lt; double &gt;", "structmodm_1_1_geometric_traits_3_01double_01_4.html", null ],
      [ "Location2D", "classmodm_1_1_location2_d.html", "classmodm_1_1_location2_d" ],
      [ "PointSet2D", "classmodm_1_1_point_set2_d.html", "classmodm_1_1_point_set2_d" ],
      [ "Ray2D", "classmodm_1_1_ray2_d.html", "classmodm_1_1_ray2_d" ],
      [ "Vector", "classmodm_1_1_vector.html", null ],
      [ "Matrix", "classmodm_1_1_matrix.html", "classmodm_1_1_matrix" ],
      [ "Quaternion", "classmodm_1_1_quaternion.html", "classmodm_1_1_quaternion" ],
      [ "Vector&lt; T, 1 &gt;", "classmodm_1_1_vector_3_01_t_00_011_01_4.html", null ],
      [ "Vector&lt; T, 2 &gt;", "classmodm_1_1_vector_3_01_t_00_012_01_4.html", "classmodm_1_1_vector_3_01_t_00_012_01_4" ],
      [ "Vector&lt; T, 3 &gt;", "classmodm_1_1_vector_3_01_t_00_013_01_4.html", null ],
      [ "Vector&lt; T, 4 &gt;", "classmodm_1_1_vector_3_01_t_00_014_01_4.html", null ],
      [ "LUDecomposition", "classmodm_1_1_l_u_decomposition.html", null ],
      [ "Saturated", "classmodm_1_1_saturated.html", "classmodm_1_1_saturated" ],
      [ "Tolerance", "classmodm_1_1_tolerance.html", null ],
      [ "CanBitTimingConfiguration", "structmodm_1_1_can_bit_timing_configuration.html", null ],
      [ "CanBitTiming", "classmodm_1_1_can_bit_timing.html", null ],
      [ "NestedResumable", "classmodm_1_1_nested_resumable.html", "classmodm_1_1_nested_resumable" ],
      [ "ResumableResult", "structmodm_1_1_resumable_result.html", "structmodm_1_1_resumable_result" ],
      [ "Resumable", "classmodm_1_1_resumable.html", "classmodm_1_1_resumable" ],
      [ "Task", "classmodm_1_1_task.html", null ],
      [ "GenericPeriodicTimer", "classmodm_1_1_generic_periodic_timer.html", "classmodm_1_1_generic_periodic_timer" ],
      [ "GenericTimeout", "classmodm_1_1_generic_timeout.html", "classmodm_1_1_generic_timeout" ],
      [ "aligned_storage", "structmodm_1_1aligned__storage.html", null ],
      [ "inplace_any", "classmodm_1_1inplace__any.html", "classmodm_1_1inplace__any" ],
      [ "get_callable_signature", "structmodm_1_1get__callable__signature.html", null ],
      [ "get_callable_signature&lt; R(*)(Args...)&gt;", "structmodm_1_1get__callable__signature_3_01_r_07_5_08_07_args_8_8_8_08_4.html", null ],
      [ "get_callable_signature&lt; R(Args...)&gt;", "structmodm_1_1get__callable__signature_3_01_r_07_args_8_8_8_08_4.html", null ],
      [ "get_callable_signature&lt; F &gt;", "structmodm_1_1get__callable__signature_3_01_f_01_4.html", null ],
      [ "bitCount", "group__modm__math__utils.html#gad44c478120365254aa1ee9387ebf7e6a", null ],
      [ "bitCount", "group__modm__math__utils.html#gae0d037914bc24d4e7d9ef3bd7875c106", null ],
      [ "bitCount", "group__modm__math__utils.html#gaf87b61c94640fb831d3e5a4c4e5d5e54", null ],
      [ "bitReverse", "group__modm__math__utils.html#ga21d50f72ee3eea7c6cfec85c9960c049", null ],
      [ "bitReverse", "group__modm__math__utils.html#ga9dde46a0dced1c1aabd0f169633540cf", null ],
      [ "bitReverse", "group__modm__math__utils.html#gaf059b757726ddbd2bd65c5cde94ea191", null ],
      [ "constexpr_fabs", "group__modm__math__utils.html#ga31a4e76db095e86012f758c64b7aa038", null ],
      [ "isBigEndian", "group__modm__math__utils.html#ga301a273e20d9bd3f736d2f6167b0b14c", null ],
      [ "isLittleEndian", "group__modm__math__utils.html#ga7c894de412bf85a4aa1267d98fa4f54d", null ],
      [ "isPositive", "group__modm__math__utils.html#gaec13941291730157912e182afefe1be0", null ],
      [ "leftmostBit", "group__modm__math__utils.html#gad8ca8a97b6f8b1f20e73ca32d717dcb7", null ],
      [ "max", "group__modm__math__utils.html#ga9724ed6e0a257a51cd7f6933927cf15d", null ],
      [ "max", "group__modm__math__utils.html#gad41810ecbe0b55aa0590d557b4f4a566", null ],
      [ "max", "group__modm__math__utils.html#gaa89d150ac3c4c69a60307dd6c39f9c23", null ],
      [ "min", "group__modm__math__utils.html#ga3a5b19e5ae348931e63e07007ca18138", null ],
      [ "min", "group__modm__math__utils.html#gae0a083563ab50699aa87ff08e61a5eed", null ],
      [ "pow", "group__modm__math__utils.html#ga5df53b0ad92fb8fa06b5dc17a16b1ed5", null ],
      [ "swap", "group__modm__math__utils.html#ga35dd3039fcb47d5867cfb1698aaa4d59", null ],
      [ "swap", "group__modm__math__utils.html#ga56b8b0a790c433b4e9792960981674e3", null ],
      [ "swap", "group__modm__math__utils.html#gadae75837321e91ad573de953e14bca6f", null ],
      [ "swap", "group__modm__math__utils.html#ga671d871cbcb60078122d969daecfa478", null ]
    ] ]
];