/*****************************************************************************/
/********** !!! WARNING: CODE GENERATED BY TAPROOT. DO NOT EDIT !!! **********/
/*****************************************************************************/

/*
 * Copyright (c) 2022-2023 Advanced Robotics at the University of Washington <robomstr@uw.edu>
 *
 * This file is part of Taproot.
 *
 * Taproot is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Taproot is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Taproot.  If not, see <https://www.gnu.org/licenses/>.
 */

#ifndef TAPROOT_INTRINSIC_EULER_EXTRACTOR_HPP_
#define TAPROOT_INTRINSIC_EULER_EXTRACTOR_HPP_

#include <array>
#include <cmath>

#include "modm/math/geometry/angle.hpp"

#include "axis.hpp"

namespace tap::algorithms::transforms
{
template <Axis...>
struct always_false : std::false_type
{
};

// Fallback for unimplemented sequences
template <Axis A, Axis B, Axis C>
struct IntrinsicEulerExtractor
{
    // this always_false templatization is needed to delay assert evaluation until template
    // parameters are known, at which point it will only fail if a specialization isn't found.
    static_assert(
        always_false<A, B, C>::value,
        "Euler sequence extraction not yet implemented for these axes! "
        "You must manually derive and add the extraction equations.");

    /**
     * @param rotation pointer to row-major rotation matrix array
     */
    static std::array<float, 3> extract(const float*) { return {}; }
};

template <>
struct IntrinsicEulerExtractor<Axis::Z, Axis::Y, Axis::X>
{
    static std::array<float, 3> extract(const float* rotation)
    {
        float angleA, angleB, angleC;
        float sin_p = -rotation[6];  // m20

        if (sin_p >= 0.999999f)
        {  // Gimbal Lock (+90 deg)
            angleA = std::atan2(-rotation[1], rotation[4]);
            angleB = M_PI_2;
            angleC = 0.0f;
        }
        else if (sin_p <= -0.999999f)
        {  // Gimbal Lock (-90 deg)
            angleA = std::atan2(-rotation[1], rotation[4]);
            angleB = -M_PI_2;
            angleC = 0.0f;
        }
        else
        {                                                   // Normal case
            angleA = std::atan2(rotation[3], rotation[0]);  // atan2(m10, m00)
            angleB = std::asin(sin_p);
            angleC = std::atan2(rotation[7], rotation[8]);  // atan2(m21, m22)
        }
        return {angleA, angleB, angleC};
    }
};

template <>
struct IntrinsicEulerExtractor<Axis::X, Axis::Y, Axis::Z>
{
    static std::array<float, 3> extract(const float* rotation)
    {
        float angleA, angleB, angleC;
        float sin_p = rotation[2];  // m02

        if (sin_p >= 0.999999f)
        {  // Gimbal Lock (+90 deg)
            angleA = 0.0f;
            angleB = M_PI_2;
            angleC = std::atan2(rotation[3], rotation[4]);
        }
        else if (sin_p <= -0.999999f)
        {  // Gimbal Lock (-90 deg)
            angleA = 0.0f;
            angleB = -M_PI_2;
            angleC = std::atan2(-rotation[3], rotation[4]);
        }
        else
        {                                                    // Normal case
            angleA = std::atan2(-rotation[5], rotation[8]);  // atan2(-m12, m22)
            angleB = std::asin(sin_p);
            angleC = std::atan2(-rotation[1], rotation[0]);  // atan2(-m01, m00)
        }
        return {angleA, angleB, angleC};
    }
};

template <>
struct IntrinsicEulerExtractor<Axis::X, Axis::Y, Axis::X>
{
    static std::array<float, 3> extract(const float* rotation)
    {
        float angleA, angleB, angleC;
        float cos_b = rotation[0];  // m00

        // sin^2(beta) = m01^2 + m02^2
        float sin_b = std::sqrt(rotation[1] * rotation[1] + rotation[2] * rotation[2]);

        // gimbal lock
        if (sin_b < 1e-6f)
        {
            if (cos_b > 0.0f)
            {
                angleA = 0.0f;
                angleB = 0.0f;
                angleC = std::atan2(rotation[7], rotation[4]);  // atan2(m21, m11)
            }
            else
            {
                angleA = 0.0f;
                angleB = M_PI;
                angleC = std::atan2(-rotation[7], rotation[4]);  // atan2(-m21, m11)
            }
        }
        else
        {
            angleA = std::atan2(rotation[3], -rotation[6]);  // atan2(m10, -m20)
            angleB = std::atan2(sin_b, cos_b);               // atan2(sin_b, cos_b)
            angleC = std::atan2(rotation[1], rotation[2]);   // atan2(m01, m02)
        }

        return {angleA, angleB, angleC};
    }
};
}  // namespace tap::algorithms::transforms
#endif  // TAPROOT_INTRINSIC_EULER_EXTRACTOR_HPP_
