/*****************************************************************************/
/********** !!! WARNING: CODE GENERATED BY TAPROOT. DO NOT EDIT !!! **********/
/*****************************************************************************/

/*
 * Copyright (c) 2020-2021 Advanced Robotics at the University of Washington <robomstr@uw.edu>
 *
 * This file is part of Taproot.
 *
 * Taproot is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Taproot is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Taproot.  If not, see <https://www.gnu.org/licenses/>.
 */

#ifndef TAPROOT_CMSIS_MAT_HPP_
#define TAPROOT_CMSIS_MAT_HPP_

#include <array>
#include <cassert>
#include <cinttypes>
#include <iostream>

#include "modm/architecture/utils.hpp"

#include "arm_math.h"

namespace tap::algorithms
{
/**
 * Wraps an `arm_mat_instance_f32` and its associated array.
 * This is done to make it clear which arrays are associated
 * with which `arm_mat_instance_f32` instances.
 */
template <uint16_t ROWS, uint16_t COLS>
struct CMSISMat
{
    std::array<float, ROWS * COLS> data;
    arm_matrix_instance_f32 matrix;

    CMSISMat() : data(), matrix{ROWS, COLS, data.data()} {}

    CMSISMat(const float (&initialData)[ROWS * COLS])
    {
        copyData(initialData);
        arm_mat_init_f32(&matrix, ROWS, COLS, data.data());
    }

    /**
     * Deep copy. Costly; use std::move to invoke move constructor whenever possible.
     */
    CMSISMat(const CMSISMat &other) : matrix{ROWS, COLS, data.data()}
    {
        memcpy(&this->data, &other.data, sizeof(this->data));
    }

    // Move semantics.
    CMSISMat(CMSISMat &&other)
    {
        this->data = std::move(other.data);
        matrix.numRows = ROWS;
        matrix.numCols = COLS;
        matrix.pData = data.data();
    }

    inline const float &operator[](int index) const { return data[index]; }
    inline float &operator[](int index) { return data[index]; }

    /**
     * Deep copy. Costly; use std::move to invoke move assignment whenever possible.
     */
    CMSISMat &operator=(const CMSISMat &other)
    {
        memcpy(&this->data, &other.data, sizeof(this->data));
        return *this;
    }

    // Move semantics.
    CMSISMat &operator=(CMSISMat &&other)
    {
        this->data = std::move(other.data);
        matrix.numRows = ROWS;
        matrix.numCols = COLS;
        matrix.pData = data.data();
        return *this;
    }

    inline void copyData(const float (&other)[ROWS * COLS])
    {
        for (size_t i = 0; i < data.size(); i++)
        {
            data[i] = other[i];
        }
    }

    /**
     * Construct identity matrix in the current CMSISMat.
     */
    bool constructIdentityMatrix()
    {
        if (ROWS != COLS)
        {
            return false;
        }

        for (int i = 0; i < ROWS; i++)
        {
            for (int j = 0; j < COLS; j++)
            {
                data[i * COLS + j] = (i == j) ? 1 : 0;
            }
        }

        return true;
    }

    inline CMSISMat<COLS, ROWS> inverse() const
    {
        CMSISMat<COLS, ROWS> ret;
        assert(ARM_MATH_SUCCESS == arm_mat_inverse_f32(&this->matrix, &ret.matrix));
        return ret;
    }

    inline CMSISMat<COLS, ROWS> transpose() const
    {
        CMSISMat<COLS, ROWS> ret;
        assert(ARM_MATH_SUCCESS == arm_mat_trans_f32(&this->matrix, &ret.matrix));
        return ret;
    }
};

/* Begin definitions */

template <uint16_t A_ROWS, uint16_t A_COLS, uint16_t B_ROWS, uint16_t B_COLS>
inline CMSISMat<A_ROWS, A_COLS> operator+(
    const CMSISMat<A_ROWS, A_COLS> &a,
    const CMSISMat<B_ROWS, B_COLS> &b)
{
    static_assert(
        A_ROWS == B_ROWS && A_COLS == B_COLS,
        "Invalid size of CMSISMat matricies in operator+");

    CMSISMat<A_ROWS, A_COLS> c;
    assert(ARM_MATH_SUCCESS == arm_mat_add_f32(&a.matrix, &b.matrix, &c.matrix));
    return c;
}

template <uint16_t A_ROWS, uint16_t A_COLS, uint16_t B_ROWS, uint16_t B_COLS>
inline CMSISMat<A_ROWS, A_COLS> operator-(
    const CMSISMat<A_ROWS, A_COLS> &a,
    const CMSISMat<B_ROWS, B_COLS> &b)
{
    static_assert(
        A_ROWS == B_ROWS && A_COLS == B_COLS,
        "Invalid size of CMSISMat matricies in operator-");

    CMSISMat<A_ROWS, A_COLS> c;
    assert(ARM_MATH_SUCCESS == arm_mat_sub_f32(&a.matrix, &b.matrix, &c.matrix));
    return c;
}

template <uint16_t ROWS, uint16_t COLS>
inline CMSISMat<ROWS, COLS> operator-(const CMSISMat<ROWS, COLS> &a)
{
    float scale(-1);
    CMSISMat<ROWS, COLS> c;
    assert(ARM_MATH_SUCCESS == arm_mat_scale_f32(&a.matrix, scale, &c.matrix));
    return c;
}

template <uint16_t A_ROWS, uint16_t A_COLS, uint16_t B_ROWS, uint16_t B_COLS>
inline CMSISMat<A_ROWS, B_COLS> operator*(
    const CMSISMat<A_ROWS, A_COLS> &a,
    const CMSISMat<B_ROWS, B_COLS> &b)
{
    static_assert(A_COLS == B_ROWS, "Invalid size of CMSISMat matricies in operator*");

    CMSISMat<A_ROWS, B_COLS> c;
    assert(ARM_MATH_SUCCESS == arm_mat_mult_f32(&a.matrix, &b.matrix, &c.matrix));
    return c;
}

template <uint16_t ROWS, uint16_t COLS>
inline CMSISMat<ROWS, COLS> operator*(const CMSISMat<ROWS, COLS> &a, float b)
{
    CMSISMat<ROWS, COLS> c;
    assert(ARM_MATH_SUCCESS == arm_mat_scale_f32(&a.matrix, b, &c.matrix));
    return c;
}

template <uint16_t ROWS, uint16_t COLS>
inline CMSISMat<ROWS, COLS> operator*(float b, const CMSISMat<ROWS, COLS> &a)
{
    CMSISMat<ROWS, COLS> c;
    assert(ARM_MATH_SUCCESS == arm_mat_scale_f32(&a.matrix, b, &c.matrix));
    return c;
}

template <uint16_t ROWS, uint16_t COLS>
inline CMSISMat<ROWS, COLS> operator/(const CMSISMat<ROWS, COLS> &a, float b)
{
    b = 1 / b;
    CMSISMat<ROWS, COLS> c;
    assert(ARM_MATH_SUCCESS == arm_mat_scale_f32(&a.matrix, b, &c.matrix));
    return c;
}

// ==============================================================================
// 3x3 Specializations
// ==============================================================================

// 3x3 Multiplication
template <>
inline CMSISMat<3, 3> operator*(const CMSISMat<3, 3> &a, const CMSISMat<3, 3> &b)
{
    CMSISMat<3, 3> c;

    const float *pA = a.matrix.pData;
    const float *pB = b.matrix.pData;
    float *pC = c.matrix.pData;

    pC[0] = pA[0] * pB[0] + pA[1] * pB[3] + pA[2] * pB[6];
    pC[1] = pA[0] * pB[1] + pA[1] * pB[4] + pA[2] * pB[7];
    pC[2] = pA[0] * pB[2] + pA[1] * pB[5] + pA[2] * pB[8];

    pC[3] = pA[3] * pB[0] + pA[4] * pB[3] + pA[5] * pB[6];
    pC[4] = pA[3] * pB[1] + pA[4] * pB[4] + pA[5] * pB[7];
    pC[5] = pA[3] * pB[2] + pA[4] * pB[5] + pA[5] * pB[8];

    pC[6] = pA[6] * pB[0] + pA[7] * pB[3] + pA[8] * pB[6];
    pC[7] = pA[6] * pB[1] + pA[7] * pB[4] + pA[8] * pB[7];
    pC[8] = pA[6] * pB[2] + pA[7] * pB[5] + pA[8] * pB[8];

    return c;
}

// 3x3 * 3x1 Multiplication
template <>
inline CMSISMat<3, 1> operator*(const CMSISMat<3, 3> &a, const CMSISMat<3, 1> &b)
{
    CMSISMat<3, 1> c;

    const float32_t *pA = a.matrix.pData;
    const float32_t *pB = b.matrix.pData;
    float32_t *pC = c.matrix.pData;

    pC[0] = pA[0] * pB[0] + pA[1] * pB[1] + pA[2] * pB[2];
    pC[1] = pA[3] * pB[0] + pA[4] * pB[1] + pA[5] * pB[2];
    pC[2] = pA[6] * pB[0] + pA[7] * pB[1] + pA[8] * pB[2];

    return c;
}

// 3x3 Addition
template <>
inline CMSISMat<3, 3> operator+(const CMSISMat<3, 3> &a, const CMSISMat<3, 3> &b)
{
    CMSISMat<3, 3> c;
    const float *pA = a.matrix.pData;
    const float *pB = b.matrix.pData;
    float *pC = c.matrix.pData;
    pC[0] = pA[0] + pB[0];
    pC[1] = pA[1] + pB[1];
    pC[2] = pA[2] + pB[2];
    pC[3] = pA[3] + pB[3];
    pC[4] = pA[4] + pB[4];
    pC[5] = pA[5] + pB[5];
    pC[6] = pA[6] + pB[6];
    pC[7] = pA[7] + pB[7];
    pC[8] = pA[8] + pB[8];
    return c;
}

// 3x3 Subtraction
template <>
inline CMSISMat<3, 3> operator-(const CMSISMat<3, 3> &a, const CMSISMat<3, 3> &b)
{
    CMSISMat<3, 3> c;
    const float *pA = a.matrix.pData;
    const float *pB = b.matrix.pData;
    float *pC = c.matrix.pData;
    pC[0] = pA[0] - pB[0];
    pC[1] = pA[1] - pB[1];
    pC[2] = pA[2] - pB[2];
    pC[3] = pA[3] - pB[3];
    pC[4] = pA[4] - pB[4];
    pC[5] = pA[5] - pB[5];
    pC[6] = pA[6] - pB[6];
    pC[7] = pA[7] - pB[7];
    pC[8] = pA[8] - pB[8];
    return c;
}

// 3x3 Negation
template <>
inline CMSISMat<3, 3> operator-(const CMSISMat<3, 3> &a)
{
    CMSISMat<3, 3> c;
    const float *pA = a.matrix.pData;
    float *pC = c.matrix.pData;
    pC[0] = -pA[0];
    pC[1] = -pA[1];
    pC[2] = -pA[2];
    pC[3] = -pA[3];
    pC[4] = -pA[4];
    pC[5] = -pA[5];
    pC[6] = -pA[6];
    pC[7] = -pA[7];
    pC[8] = -pA[8];
    return c;
}

// 3x3 Scalar Multiplication
template <>
inline CMSISMat<3, 3> operator*(const CMSISMat<3, 3> &a, float b)
{
    CMSISMat<3, 3> c;
    const float *pA = a.matrix.pData;
    float *pC = c.matrix.pData;
    pC[0] = pA[0] * b;
    pC[1] = pA[1] * b;
    pC[2] = pA[2] * b;
    pC[3] = pA[3] * b;
    pC[4] = pA[4] * b;
    pC[5] = pA[5] * b;
    pC[6] = pA[6] * b;
    pC[7] = pA[7] * b;
    pC[8] = pA[8] * b;
    return c;
}

template <>
inline CMSISMat<3, 3> operator*(float b, const CMSISMat<3, 3> &a)
{
    return a * b;  // Reuse previous implementation
}

// 3x3 Scalar Division
template <>
inline CMSISMat<3, 3> operator/(const CMSISMat<3, 3> &a, float b)
{
    CMSISMat<3, 3> c;
    const float *pA = a.matrix.pData;
    float *pC = c.matrix.pData;
    float invB = 1.0f / b;
    pC[0] = pA[0] * invB;
    pC[1] = pA[1] * invB;
    pC[2] = pA[2] * invB;
    pC[3] = pA[3] * invB;
    pC[4] = pA[4] * invB;
    pC[5] = pA[5] * invB;
    pC[6] = pA[6] * invB;
    pC[7] = pA[7] * invB;
    pC[8] = pA[8] * invB;
    return c;
}

// ==============================================================================
// 3x1 Specializations
// ==============================================================================

// 3x1 Addition
template <>
inline CMSISMat<3, 1> operator+(const CMSISMat<3, 1> &a, const CMSISMat<3, 1> &b)
{
    CMSISMat<3, 1> c;
    const float *pA = a.matrix.pData;
    const float *pB = b.matrix.pData;
    float *pC = c.matrix.pData;
    pC[0] = pA[0] + pB[0];
    pC[1] = pA[1] + pB[1];
    pC[2] = pA[2] + pB[2];
    return c;
}

// 3x1 Subtraction
template <>
inline CMSISMat<3, 1> operator-(const CMSISMat<3, 1> &a, const CMSISMat<3, 1> &b)
{
    CMSISMat<3, 1> c;
    const float *pA = a.matrix.pData;
    const float *pB = b.matrix.pData;
    float *pC = c.matrix.pData;
    pC[0] = pA[0] - pB[0];
    pC[1] = pA[1] - pB[1];
    pC[2] = pA[2] - pB[2];
    return c;
}

// 3x1 Negation
template <>
inline CMSISMat<3, 1> operator-(const CMSISMat<3, 1> &a)
{
    CMSISMat<3, 1> c;
    const float *pA = a.matrix.pData;
    float *pC = c.matrix.pData;
    pC[0] = -pA[0];
    pC[1] = -pA[1];
    pC[2] = -pA[2];
    return c;
}

// 3x1 Scalar Multiplication
template <>
inline CMSISMat<3, 1> operator*(const CMSISMat<3, 1> &a, float b)
{
    CMSISMat<3, 1> c;
    const float *pA = a.matrix.pData;
    float *pC = c.matrix.pData;
    pC[0] = pA[0] * b;
    pC[1] = pA[1] * b;
    pC[2] = pA[2] * b;
    return c;
}

template <>
inline CMSISMat<3, 1> operator*(float b, const CMSISMat<3, 1> &a)
{
    return a * b;  // Reuse previous implementation
}

// 3x1 Scalar Division
template <>
inline CMSISMat<3, 1> operator/(const CMSISMat<3, 1> &a, float b)
{
    CMSISMat<3, 1> c;
    const float *pA = a.matrix.pData;
    float *pC = c.matrix.pData;
    float invB = 1.0f / b;
    pC[0] = pA[0] * invB;
    pC[1] = pA[1] * invB;
    pC[2] = pA[2] * invB;
    return c;
}

template <>
inline CMSISMat<3, 3> CMSISMat<3, 3>::transpose() const
{
    CMSISMat<3, 3> ret;

    const float *pA = this->matrix.pData;
    float *pRet = ret.matrix.pData;

    // The diagonal remains unchanged
    pRet[0] = pA[0];
    pRet[4] = pA[4];
    pRet[8] = pA[8];

    // Swap the off-diagonal elements
    pRet[1] = pA[3];
    pRet[3] = pA[1];

    pRet[2] = pA[6];
    pRet[6] = pA[2];

    pRet[5] = pA[7];
    pRet[7] = pA[5];

    return ret;
}

}  // namespace tap::algorithms

#endif  // TAPROOT_CMSIS_MAT_HPP_
