# Copyright (c) 2020-2021 Advanced Robotics at the University of Washington <robomstr@uw.edu>
#
# This file is part of Taproot.
#
# Taproot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Taproot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Taproot.  If not, see <https://www.gnu.org/licenses/>.

Import("env")

from os.path import abspath

files = env.FindSourceFiles(".")

if len(files) != 0:
    newenv = env.Clone()
    newenv.Append(CCFLAGS=["-w"]) # suppress all warnings
    library = newenv.StaticLibrary(target="taproot-ext", source=files)

    env.AppendUnique(LIBPATH=[
        abspath(str(library[0].get_dir())),
    ])

    env.AppendUnique(LIBS=[
        library,
    ])

    Return("library")
